if SERVER then
    resource.AddFile( "models/player/clanof05/male_02.mdl" )
    resource.AddFile( "models/player/clanof05/male_02.dx80.vtx" )
    resource.AddFile( "models/player/clanof05/male_02.dx90.vtx" )
    resource.AddFile( "models/player/clanof05/male_02.sw.vtx" )
    resource.AddFile( "models/player/clanof05/male_02.vvd" )
    resource.AddFile( "models/player/clanof05/male_02.phy" )
    resource.AddFile( "models/player/clanof05/male_04.mdl" )
    resource.AddFile( "models/player/clanof05/male_04.dx80.vtx" )
    resource.AddFile( "models/player/clanof05/male_04.dx90.vtx" )
    resource.AddFile( "models/player/clanof05/male_04.sw.vtx" )
    resource.AddFile( "models/player/clanof05/male_04.vvd" )
    resource.AddFile( "models/player/clanof05/male_04.phy" )
    resource.AddFile( "models/player/clanof05/male_05.mdl" )
    resource.AddFile( "models/player/clanof05/male_05.dx80.vtx" )
    resource.AddFile( "models/player/clanof05/male_05.dx90.vtx" )
    resource.AddFile( "models/player/clanof05/male_05.sw.vtx" )
    resource.AddFile( "models/player/clanof05/male_05.vvd" )
    resource.AddFile( "models/player/clanof05/male_05.phy" )
    resource.AddFile( "models/player/clanof05/male_06.mdl" )
    resource.AddFile( "models/player/clanof05/male_06.dx80.vtx" )
    resource.AddFile( "models/player/clanof05/male_06.dx90.vtx" )
    resource.AddFile( "models/player/clanof05/male_06.sw.vtx" )
    resource.AddFile( "models/player/clanof05/male_06.vvd" )
    resource.AddFile( "models/player/clanof05/male_06.phy" )
    resource.AddFile( "models/player/clanof05/male_08.mdl" )
    resource.AddFile( "models/player/clanof05/male_08.dx80.vtx" )
    resource.AddFile( "models/player/clanof05/male_08.dx90.vtx" )
    resource.AddFile( "models/player/clanof05/male_08.sw.vtx" )
    resource.AddFile( "models/player/clanof05/male_08.vvd" )
    resource.AddFile( "models/player/clanof05/male_08.phy" )
    resource.AddFile( "models/player/clanof05/male_09.mdl" )
    resource.AddFile( "models/player/clanof05/male_09.dx80.vtx" )
    resource.AddFile( "models/player/clanof05/male_09.dx90.vtx" )
    resource.AddFile( "models/player/clanof05/male_09.sw.vtx" )
    resource.AddFile( "models/player/clanof05/male_09.vvd" )
    resource.AddFile( "models/player/clanof05/male_09.phy" )
end

player_manager.AddValidModel( "Summermale_02_05", "models/player/clanof05/male_02.mdl" )
list.Set( "PlayerOptionsModel", "Summermale_02_05", "models/player/clanof05/male_02.mdl" )
player_manager.AddValidModel( "Summermale_04_05", "models/player/clanof05/male_04.mdl" )
list.Set( "PlayerOptionsModel", "Summermale_04_05", "models/player/clanof05/male_04.mdl" )
player_manager.AddValidModel( "Summermale_05_05", "models/player/clanof05/male_05.mdl" )
list.Set( "PlayerOptionsModel", "Summermale_05_05", "models/player/clanof05/male_05.mdl" )
player_manager.AddValidModel( "Summermale_06_05", "models/player/clanof05/male_06.mdl" )
list.Set( "PlayerOptionsModel", "Summermale_06_05", "models/player/clanof05/male_06.mdl" )
player_manager.AddValidModel( "Summermale_08_05", "models/player/clanof05/male_08.mdl" )
list.Set( "PlayerOptionsModel", "Summermale_08_05", "models/player/clanof05/male_08.mdl" )
player_manager.AddValidModel( "Summermale_09_05", "models/player/clanof05/male_09.mdl" )
list.Set( "PlayerOptionsModel", "Summermale_09_05", "models/player/clanof05/male_09.mdl" )
