if SERVER then
    resource.AddFile( "models/player/tuxmale_01player.mdl" )
    resource.AddFile( "models/player/tuxmale_01player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_01player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_01player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_01player.vvd" )
    resource.AddFile( "models/player/tuxmale_01player.phy" )
    resource.AddFile( "models/player/tuxmale_02player.mdl" )
    resource.AddFile( "models/player/tuxmale_02player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_02player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_02player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_02player.vvd" )
    resource.AddFile( "models/player/tuxmale_02player.phy" )
    resource.AddFile( "models/player/tuxmale_03player.mdl" )
    resource.AddFile( "models/player/tuxmale_03player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_03player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_03player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_03player.vvd" )
    resource.AddFile( "models/player/tuxmale_03player.phy" )
    resource.AddFile( "models/player/tuxmale_04player.mdl" )
    resource.AddFile( "models/player/tuxmale_04player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_04player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_04player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_04player.vvd" )
    resource.AddFile( "models/player/tuxmale_04player.phy" )
    resource.AddFile( "models/player/tuxmale_05player.mdl" )
    resource.AddFile( "models/player/tuxmale_05player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_05player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_05player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_05player.vvd" )
    resource.AddFile( "models/player/tuxmale_05player.phy" )
    resource.AddFile( "models/player/tuxmale_06player.mdl" )
    resource.AddFile( "models/player/tuxmale_06player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_06player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_06player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_06player.vvd" )
    resource.AddFile( "models/player/tuxmale_06player.phy" )
    resource.AddFile( "models/player/tuxmale_07player.mdl" )
    resource.AddFile( "models/player/tuxmale_07player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_07player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_07player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_07player.vvd" )
    resource.AddFile( "models/player/tuxmale_07player.phy" )
    resource.AddFile( "models/player/tuxmale_08player.mdl" )
    resource.AddFile( "models/player/tuxmale_08player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_08player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_08player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_08player.vvd" )
    resource.AddFile( "models/player/tuxmale_08player.phy" )
    resource.AddFile( "models/player/tuxmale_09player.mdl" )
    resource.AddFile( "models/player/tuxmale_09player.dx80.vtx" )
    resource.AddFile( "models/player/tuxmale_09player.dx90.vtx" )
    resource.AddFile( "models/player/tuxmale_09player.sw.vtx" )
    resource.AddFile( "models/player/tuxmale_09player.vvd" )
    resource.AddFile( "models/player/tuxmale_09player.phy" )
end

list.Set( "PlayerOptionsModel", "tuxmale_01", "models/player/tuxmale_01player.mdl" )
player_manager.AddValidModel( "tuxmale_01", "models/player/tuxmale_01player.mdl" )
list.Set( "PlayerOptionsModel", "tuxmale_02", "models/player/tuxmale_02player.mdl" )
player_manager.AddValidModel( "tuxmale_02", "models/player/tuxmale_02player.mdl" )
list.Set( "PlayerOptionsModel", "tuxmale_03", "models/player/tuxmale_03player.mdl" )
player_manager.AddValidModel( "tuxmale_03", "models/player/tuxmale_03player.mdl" )
list.Set( "PlayerOptionsModel", "tuxmale_04", "models/player/tuxmale_04player.mdl" )
player_manager.AddValidModel( "tuxmale_04", "models/player/tuxmale_04player.mdl" )
list.Set( "PlayerOptionsModel", "tuxmale_05", "models/player/tuxmale_05player.mdl" )
player_manager.AddValidModel( "tuxmale_05", "models/player/tuxmale_05player.mdl" )
list.Set( "PlayerOptionsModel", "tuxmale_06", "models/player/tuxmale_06player.mdl" )
player_manager.AddValidModel( "tuxmale_06", "models/player/tuxmale_06player.mdl" )
list.Set( "PlayerOptionsModel", "tuxmale_07", "models/player/tuxmale_07player.mdl" )
player_manager.AddValidModel( "tuxmale_07", "models/player/tuxmale_07player.mdl" )
list.Set( "PlayerOptionsModel", "tuxmale_08", "models/player/tuxmale_08player.mdl" )
player_manager.AddValidModel( "tuxmale_08", "models/player/tuxmale_08player.mdl" )
list.Set( "PlayerOptionsModel", "tuxmale_09", "models/player/tuxmale_09player.mdl" )
player_manager.AddValidModel( "tuxmale_09", "models/player/tuxmale_09player.mdl" )
