if SERVER then
    resource.AddFile( "models/katy/npc/merriweather/male_01_enemy.mdl" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_enemy.dx80.vtx" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_enemy.dx90.vtx" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_enemy.sw.vtx" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_enemy.vvd" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_enemy.phy" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_friend.mdl" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_friend.dx80.vtx" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_friend.dx90.vtx" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_friend.sw.vtx" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_friend.vvd" )
    resource.AddFile( "models/katy/npc/merriweather/male_01_friend.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_01.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_01.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_01.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_01.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_01.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_01.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_02.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_02.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_02.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_02.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_02.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_02.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_03.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_03.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_03.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_03.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_03.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_03.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_04.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_04.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_04.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_04.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_04.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_04.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_05.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_05.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_05.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_05.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_05.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_05.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_06.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_06.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_06.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_06.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_06.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_06.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_07.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_07.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_07.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_07.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_07.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_07.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_08.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_08.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_08.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_08.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_08.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_08.phy" )
    resource.AddFile( "models/kerry/player/merriweather/male_09.mdl" )
    resource.AddFile( "models/kerry/player/merriweather/male_09.dx80.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_09.dx90.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_09.sw.vtx" )
    resource.AddFile( "models/kerry/player/merriweather/male_09.vvd" )
    resource.AddFile( "models/kerry/player/merriweather/male_09.phy" )
end

player_manager.AddValidModel( "Merriweather 1","models/kerry/player/merriweather/male_01.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 1","models/kerry/player/merriweather/male_01.mdl" )
player_manager.AddValidModel( "Merriweather 2","models/kerry/player/merriweather/male_02.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 2","models/kerry/player/merriweather/male_02.mdl" )
player_manager.AddValidModel( "Merriweather 3","models/kerry/player/merriweather/male_03.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 3","models/kerry/player/merriweather/male_03.mdl" )
player_manager.AddValidModel( "Merriweather 4","models/kerry/player/merriweather/male_04.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 4","models/kerry/player/merriweather/male_04.mdl" )
player_manager.AddValidModel( "Merriweather 5","models/kerry/player/merriweather/male_05.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 5","models/kerry/player/merriweather/male_05.mdl" )
player_manager.AddValidModel( "Merriweather 6","models/kerry/player/merriweather/male_06.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 6","models/kerry/player/merriweather/male_06.mdl" )
player_manager.AddValidModel( "Merriweather 7","models/kerry/player/merriweather/male_07.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 7","models/kerry/player/merriweather/male_07.mdl" )
player_manager.AddValidModel( "Merriweather 8","models/kerry/player/merriweather/male_08.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 8","models/kerry/player/merriweather/male_08.mdl" )
player_manager.AddValidModel( "Merriweather 9","models/kerry/player/merriweather/male_09.mdl" )
list.Set( "PlayerOptionsModel","Merriweather 9","models/kerry/player/merriweather/male_09.mdl" )
local Category = "Merriweather NPCs"
local NPC = { 	Name = "Merriweather Frend",
				Class = "npc_citizen",
				Model = "models/katy/npc/merriweather/male_01_friend.mdl",
				Health = "100",
				KeyValues = { citizentype = 4 },
                                Category = Category    }
list.Set( "NPC", "merriweather_1", NPC )
local Category = "Merriweather NPCs"
local NPC = { 	Name = "Merriweather Hostile",
				Class = "npc_combine_s",
				Model = "models/katy/npc/merriweather/male_01_enemy.mdl",
				Health = "100",
				KeyValues = { citizentype = 4 },
                                Category = Category    }
list.Set( "NPC", "merriweather_2", NPC )
