if SERVER then
    resource.AddFile( "models/player/santosrp/male_02_santosrp.mdl" )
    resource.AddFile( "models/player/santosrp/male_02_santosrp.dx80.vtx" )
    resource.AddFile( "models/player/santosrp/male_02_santosrp.dx90.vtx" )
    resource.AddFile( "models/player/santosrp/male_02_santosrp.sw.vtx" )
    resource.AddFile( "models/player/santosrp/male_02_santosrp.vvd" )
    resource.AddFile( "models/player/santosrp/male_02_santosrp.phy" )
    resource.AddFile( "models/player/santosrp/male_04_santosrp.mdl" )
    resource.AddFile( "models/player/santosrp/male_04_santosrp.dx80.vtx" )
    resource.AddFile( "models/player/santosrp/male_04_santosrp.dx90.vtx" )
    resource.AddFile( "models/player/santosrp/male_04_santosrp.sw.vtx" )
    resource.AddFile( "models/player/santosrp/male_04_santosrp.vvd" )
    resource.AddFile( "models/player/santosrp/male_04_santosrp.phy" )
    resource.AddFile( "models/player/santosrp/male_05_santosrp.mdl" )
    resource.AddFile( "models/player/santosrp/male_05_santosrp.dx80.vtx" )
    resource.AddFile( "models/player/santosrp/male_05_santosrp.dx90.vtx" )
    resource.AddFile( "models/player/santosrp/male_05_santosrp.sw.vtx" )
    resource.AddFile( "models/player/santosrp/male_05_santosrp.vvd" )
    resource.AddFile( "models/player/santosrp/male_05_santosrp.phy" )
    resource.AddFile( "models/player/santosrp/male_06_santosrp.mdl" )
    resource.AddFile( "models/player/santosrp/male_06_santosrp.dx80.vtx" )
    resource.AddFile( "models/player/santosrp/male_06_santosrp.dx90.vtx" )
    resource.AddFile( "models/player/santosrp/male_06_santosrp.sw.vtx" )
    resource.AddFile( "models/player/santosrp/male_06_santosrp.vvd" )
    resource.AddFile( "models/player/santosrp/male_06_santosrp.phy" )
    resource.AddFile( "models/player/santosrp/male_07_santosrp.mdl" )
    resource.AddFile( "models/player/santosrp/male_07_santosrp.dx80.vtx" )
    resource.AddFile( "models/player/santosrp/male_07_santosrp.dx90.vtx" )
    resource.AddFile( "models/player/santosrp/male_07_santosrp.sw.vtx" )
    resource.AddFile( "models/player/santosrp/male_07_santosrp.vvd" )
    resource.AddFile( "models/player/santosrp/male_07_santosrp.phy" )
    resource.AddFile( "models/player/santosrp/male_08_santosrp.mdl" )
    resource.AddFile( "models/player/santosrp/male_08_santosrp.dx80.vtx" )
    resource.AddFile( "models/player/santosrp/male_08_santosrp.dx90.vtx" )
    resource.AddFile( "models/player/santosrp/male_08_santosrp.sw.vtx" )
    resource.AddFile( "models/player/santosrp/male_08_santosrp.vvd" )
    resource.AddFile( "models/player/santosrp/male_08_santosrp.phy" )
    resource.AddFile( "models/player/santosrp/male_09_santosrp.mdl" )
    resource.AddFile( "models/player/santosrp/male_09_santosrp.dx80.vtx" )
    resource.AddFile( "models/player/santosrp/male_09_santosrp.dx90.vtx" )
    resource.AddFile( "models/player/santosrp/male_09_santosrp.sw.vtx" )
    resource.AddFile( "models/player/santosrp/male_09_santosrp.vvd" )
    resource.AddFile( "models/player/santosrp/male_09_santosrp.phy" )
end

player_manager.AddValidModel( "Police_1", "models/player/santosrp/Male_02_santosrp.mdl" )
list.Set( "PlayerOptionsModel", "Police_1", "models/player/santosrp/Male_02_santosrp.mdl" )
player_manager.AddValidModel( "Police_2", "models/player/santosrp/Male_04_santosrp.mdl" )
list.Set( "PlayerOptionsModel", "Police_2", "models/player/santosrp/Male_04_santosrp.mdl" )
player_manager.AddValidModel( "Police_3", "models/player/santosrp/Male_05_santosrp.mdl" )
list.Set( "PlayerOptionsModel", "Police_3", "models/player/santosrp/Male_05_santosrp.mdl" )
player_manager.AddValidModel( "Police_4", "models/player/santosrp/Male_06_santosrp.mdl" )
list.Set( "PlayerOptionsModel", "Police_4", "models/player/santosrp/Male_06_santosrp.mdl" )
player_manager.AddValidModel( "Police_5", "models/player/santosrp/Male_07_santosrp.mdl" )
list.Set( "PlayerOptionsModel", "Police_5", "models/player/santosrp/Male_07_santosrp.mdl" )
player_manager.AddValidModel( "Police_6", "models/player/santosrp/Male_08_santosrp.mdl" )
list.Set( "PlayerOptionsModel", "Police_6", "models/player/santosrp/Male_08_santosrp.mdl" )
player_manager.AddValidModel( "Police_7", "models/player/santosrp/Male_09_santosrp.mdl" )
list.Set( "PlayerOptionsModel", "Police_7", "models/player/santosrp/Male_09_santosrp.mdl" )
