if SERVER then
    resource.AddFile( "models/player/suits/male_01_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_01_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_01_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_01_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_01_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_01_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_01_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_01_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_01_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_01_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_01_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_01_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_01_open.mdl" )
    resource.AddFile( "models/player/suits/male_01_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_01_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_01_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_01_open.vvd" )
    resource.AddFile( "models/player/suits/male_01_open.phy" )
    resource.AddFile( "models/player/suits/male_01_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_01_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_01_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_01_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_01_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_01_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_01_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_01_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_01_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_01_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_01_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_01_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_01_shirt.mdl" )
    resource.AddFile( "models/player/suits/male_01_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_01_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_01_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/male_01_shirt.vvd" )
    resource.AddFile( "models/player/suits/male_01_shirt.phy" )
    resource.AddFile( "models/player/suits/male_01_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_01_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_01_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_01_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_01_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_01_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/male_02_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_02_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_02_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_02_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_02_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_02_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_02_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_02_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_02_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_02_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_02_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_02_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_02_open.mdl" )
    resource.AddFile( "models/player/suits/male_02_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_02_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_02_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_02_open.vvd" )
    resource.AddFile( "models/player/suits/male_02_open.phy" )
    resource.AddFile( "models/player/suits/male_02_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_02_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_02_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_02_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_02_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_02_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_02_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_02_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_02_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_02_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_02_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_02_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_02_shirt.mdl" )
    resource.AddFile( "models/player/suits/male_02_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_02_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_02_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/male_02_shirt.vvd" )
    resource.AddFile( "models/player/suits/male_02_shirt.phy" )
    resource.AddFile( "models/player/suits/male_02_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_02_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_02_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_02_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_02_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_02_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/male_03_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_03_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_03_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_03_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_03_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_03_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_03_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_03_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_03_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_03_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_03_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_03_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_03_open.mdl" )
    resource.AddFile( "models/player/suits/male_03_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_03_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_03_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_03_open.vvd" )
    resource.AddFile( "models/player/suits/male_03_open.phy" )
    resource.AddFile( "models/player/suits/male_03_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_03_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_03_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_03_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_03_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_03_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_03_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_03_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_03_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_03_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_03_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_03_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_03_shirt.mdl" )
    resource.AddFile( "models/player/suits/male_03_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_03_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_03_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/male_03_shirt.vvd" )
    resource.AddFile( "models/player/suits/male_03_shirt.phy" )
    resource.AddFile( "models/player/suits/male_03_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_03_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_03_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_03_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_03_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_03_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/male_04_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_04_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_04_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_04_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_04_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_04_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_04_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_04_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_04_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_04_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_04_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_04_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_04_open.mdl" )
    resource.AddFile( "models/player/suits/male_04_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_04_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_04_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_04_open.vvd" )
    resource.AddFile( "models/player/suits/male_04_open.phy" )
    resource.AddFile( "models/player/suits/male_04_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_04_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_04_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_04_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_04_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_04_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_04_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_04_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_04_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_04_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_04_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_04_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_04_shirt.mdl" )
    resource.AddFile( "models/player/suits/male_04_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_04_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_04_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/male_04_shirt.vvd" )
    resource.AddFile( "models/player/suits/male_04_shirt.phy" )
    resource.AddFile( "models/player/suits/male_04_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_04_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_04_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_04_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_04_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_04_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/male_05_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_05_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_05_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_05_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_05_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_05_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_05_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_05_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_05_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_05_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_05_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_05_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_05_open.mdl" )
    resource.AddFile( "models/player/suits/male_05_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_05_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_05_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_05_open.vvd" )
    resource.AddFile( "models/player/suits/male_05_open.phy" )
    resource.AddFile( "models/player/suits/male_05_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_05_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_05_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_05_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_05_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_05_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_05_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_05_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_05_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_05_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_05_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_05_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_05_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_05_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_05_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_05_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_05_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_05_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/male_06_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_06_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_06_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_06_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_06_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_06_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_06_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_06_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_06_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_06_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_06_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_06_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_06_open.mdl" )
    resource.AddFile( "models/player/suits/male_06_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_06_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_06_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_06_open.vvd" )
    resource.AddFile( "models/player/suits/male_06_open.phy" )
    resource.AddFile( "models/player/suits/male_06_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_06_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_06_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_06_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_06_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_06_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_06_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_06_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_06_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_06_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_06_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_06_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_06_shirt.mdl" )
    resource.AddFile( "models/player/suits/male_06_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_06_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_06_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/male_06_shirt.vvd" )
    resource.AddFile( "models/player/suits/male_06_shirt.phy" )
    resource.AddFile( "models/player/suits/male_06_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_06_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_06_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_06_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_06_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_06_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/male_07_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_07_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_07_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_07_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_07_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_07_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_07_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_07_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_07_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_07_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_07_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_07_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_07_open.mdl" )
    resource.AddFile( "models/player/suits/male_07_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_07_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_07_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_07_open.vvd" )
    resource.AddFile( "models/player/suits/male_07_open.phy" )
    resource.AddFile( "models/player/suits/male_07_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_07_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_07_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_07_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_07_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_07_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_07_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_07_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_07_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_07_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_07_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_07_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_07_shirt.mdl" )
    resource.AddFile( "models/player/suits/male_07_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_07_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_07_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/male_07_shirt.vvd" )
    resource.AddFile( "models/player/suits/male_07_shirt.phy" )
    resource.AddFile( "models/player/suits/male_07_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_07_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_07_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_07_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_07_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_07_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/male_08_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_08_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_08_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_08_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_08_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_08_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_08_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_08_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_08_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_08_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_08_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_08_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_08_open.mdl" )
    resource.AddFile( "models/player/suits/male_08_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_08_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_08_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_08_open.vvd" )
    resource.AddFile( "models/player/suits/male_08_open.phy" )
    resource.AddFile( "models/player/suits/male_08_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_08_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_08_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_08_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_08_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_08_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_08_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_08_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_08_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_08_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_08_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_08_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_08_shirt.mdl" )
    resource.AddFile( "models/player/suits/male_08_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_08_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_08_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/male_08_shirt.vvd" )
    resource.AddFile( "models/player/suits/male_08_shirt.phy" )
    resource.AddFile( "models/player/suits/male_08_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_08_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_08_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_08_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_08_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_08_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/male_09_closed_coat_tie.mdl" )
    resource.AddFile( "models/player/suits/male_09_closed_coat_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_09_closed_coat_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_09_closed_coat_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_09_closed_coat_tie.vvd" )
    resource.AddFile( "models/player/suits/male_09_closed_coat_tie.phy" )
    resource.AddFile( "models/player/suits/male_09_closed_tie.mdl" )
    resource.AddFile( "models/player/suits/male_09_closed_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_09_closed_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_09_closed_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_09_closed_tie.vvd" )
    resource.AddFile( "models/player/suits/male_09_closed_tie.phy" )
    resource.AddFile( "models/player/suits/male_09_open.mdl" )
    resource.AddFile( "models/player/suits/male_09_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_09_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_09_open.sw.vtx" )
    resource.AddFile( "models/player/suits/male_09_open.vvd" )
    resource.AddFile( "models/player/suits/male_09_open.phy" )
    resource.AddFile( "models/player/suits/male_09_open_tie.mdl" )
    resource.AddFile( "models/player/suits/male_09_open_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_09_open_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_09_open_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_09_open_tie.vvd" )
    resource.AddFile( "models/player/suits/male_09_open_tie.phy" )
    resource.AddFile( "models/player/suits/male_09_open_waistcoat.mdl" )
    resource.AddFile( "models/player/suits/male_09_open_waistcoat.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_09_open_waistcoat.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_09_open_waistcoat.sw.vtx" )
    resource.AddFile( "models/player/suits/male_09_open_waistcoat.vvd" )
    resource.AddFile( "models/player/suits/male_09_open_waistcoat.phy" )
    resource.AddFile( "models/player/suits/male_09_shirt.mdl" )
    resource.AddFile( "models/player/suits/male_09_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_09_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_09_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/male_09_shirt.vvd" )
    resource.AddFile( "models/player/suits/male_09_shirt.phy" )
    resource.AddFile( "models/player/suits/male_09_shirt_tie.mdl" )
    resource.AddFile( "models/player/suits/male_09_shirt_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/male_09_shirt_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/male_09_shirt_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/male_09_shirt_tie.vvd" )
    resource.AddFile( "models/player/suits/male_09_shirt_tie.phy" )
    resource.AddFile( "models/player/suits/robber_open.mdl" )
    resource.AddFile( "models/player/suits/robber_open.dx80.vtx" )
    resource.AddFile( "models/player/suits/robber_open.dx90.vtx" )
    resource.AddFile( "models/player/suits/robber_open.sw.vtx" )
    resource.AddFile( "models/player/suits/robber_open.vvd" )
    resource.AddFile( "models/player/suits/robber_open.phy" )
    resource.AddFile( "models/player/suits/robber_shirt.mdl" )
    resource.AddFile( "models/player/suits/robber_shirt.dx80.vtx" )
    resource.AddFile( "models/player/suits/robber_shirt.dx90.vtx" )
    resource.AddFile( "models/player/suits/robber_shirt.sw.vtx" )
    resource.AddFile( "models/player/suits/robber_shirt.vvd" )
    resource.AddFile( "models/player/suits/robber_shirt.phy" )
    resource.AddFile( "models/player/suits/robber_shirt_2.mdl" )
    resource.AddFile( "models/player/suits/robber_shirt_2.dx80.vtx" )
    resource.AddFile( "models/player/suits/robber_shirt_2.dx90.vtx" )
    resource.AddFile( "models/player/suits/robber_shirt_2.sw.vtx" )
    resource.AddFile( "models/player/suits/robber_shirt_2.vvd" )
    resource.AddFile( "models/player/suits/robber_shirt_2.phy" )
    resource.AddFile( "models/player/suits/robber_tie.mdl" )
    resource.AddFile( "models/player/suits/robber_tie.dx80.vtx" )
    resource.AddFile( "models/player/suits/robber_tie.dx90.vtx" )
    resource.AddFile( "models/player/suits/robber_tie.sw.vtx" )
    resource.AddFile( "models/player/suits/robber_tie.vvd" )
    resource.AddFile( "models/player/suits/robber_tie.phy" )
    resource.AddFile( "models/player/suits/robber_tuckedtie.mdl" )
    resource.AddFile( "models/player/suits/robber_tuckedtie.dx80.vtx" )
    resource.AddFile( "models/player/suits/robber_tuckedtie.dx90.vtx" )
    resource.AddFile( "models/player/suits/robber_tuckedtie.sw.vtx" )
    resource.AddFile( "models/player/suits/robber_tuckedtie.vvd" )
    resource.AddFile( "models/player/suits/robber_tuckedtie.phy" )
end

player_manager.AddValidModel( "Suit_1a", "models/player/Suits/male_01_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_1a", "models/player/Suits/male_01_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_1b", "models/player/Suits/male_01_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_1b", "models/player/Suits/male_01_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_1c", "models/player/Suits/male_01_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_1c", "models/player/Suits/male_01_open.mdl" )
player_manager.AddValidModel( "Suit_1d", "models/player/Suits/male_01_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_1d", "models/player/Suits/male_01_open_tie.mdl" )
player_manager.AddValidModel( "Suit_1e", "models/player/Suits/male_01_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_1e", "models/player/Suits/male_01_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_1f", "models/player/Suits/male_01_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Suit_1f", "models/player/Suits/male_01_shirt.mdl" )
player_manager.AddValidModel( "Suit_1g", "models/player/Suits/male_01_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_1g", "models/player/Suits/male_01_shirt_tie.mdl" )
player_manager.AddValidModel( "Suit_2a", "models/player/Suits/male_02_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_2a", "models/player/Suits/male_02_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_2b", "models/player/Suits/male_02_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_2b", "models/player/Suits/male_02_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_2c", "models/player/Suits/male_02_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_2c", "models/player/Suits/male_02_open.mdl" )
player_manager.AddValidModel( "Suit_2d", "models/player/Suits/male_02_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_2d", "models/player/Suits/male_02_open_tie.mdl" )
player_manager.AddValidModel( "Suit_2e", "models/player/Suits/male_02_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_2e", "models/player/Suits/male_02_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_2f", "models/player/Suits/male_02_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Suit_2f", "models/player/Suits/male_02_shirt.mdl" )
player_manager.AddValidModel( "Suit_2g", "models/player/Suits/male_02_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_2g", "models/player/Suits/male_02_shirt_tie.mdl" )
player_manager.AddValidModel( "Suit_3a", "models/player/Suits/male_03_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_3a", "models/player/Suits/male_03_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_3b", "models/player/Suits/male_03_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_3b", "models/player/Suits/male_03_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_3c", "models/player/Suits/male_03_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_3c", "models/player/Suits/male_03_open.mdl" )
player_manager.AddValidModel( "Suit_3d", "models/player/Suits/male_03_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_3d", "models/player/Suits/male_03_open_tie.mdl" )
player_manager.AddValidModel( "Suit_3e", "models/player/Suits/male_03_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_3e", "models/player/Suits/male_03_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_3f", "models/player/Suits/male_03_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Suit_3f", "models/player/Suits/male_03_shirt.mdl" )
player_manager.AddValidModel( "Suit_3g", "models/player/Suits/male_03_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_3g", "models/player/Suits/male_03_shirt_tie.mdl" )
player_manager.AddValidModel( "Suit_4a", "models/player/Suits/male_04_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_4a", "models/player/Suits/male_04_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_4b", "models/player/Suits/male_04_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_4b", "models/player/Suits/male_04_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_4c", "models/player/Suits/male_04_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_4c", "models/player/Suits/male_04_open.mdl" )
player_manager.AddValidModel( "Suit_4d", "models/player/Suits/male_04_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_4d", "models/player/Suits/male_04_open_tie.mdl" )
player_manager.AddValidModel( "Suit_4e", "models/player/Suits/male_04_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_4e", "models/player/Suits/male_04_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_4f", "models/player/Suits/male_04_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Suit_4f", "models/player/Suits/male_04_shirt.mdl" )
player_manager.AddValidModel( "Suit_4g", "models/player/Suits/male_04_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_4g", "models/player/Suits/male_04_shirt_tie.mdl" )
player_manager.AddValidModel( "Suit_5a", "models/player/Suits/male_05_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_5a", "models/player/Suits/male_05_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_5b", "models/player/Suits/male_05_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_5b", "models/player/Suits/male_05_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_5c", "models/player/Suits/male_05_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_5c", "models/player/Suits/male_05_open.mdl" )
player_manager.AddValidModel( "Suit_5d", "models/player/Suits/male_05_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_5d", "models/player/Suits/male_05_open_tie.mdl" )
player_manager.AddValidModel( "Suit_5e", "models/player/Suits/male_05_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_5e", "models/player/Suits/male_05_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_5g", "models/player/Suits/male_05_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_5g", "models/player/Suits/male_05_shirt_tie.mdl" )
player_manager.AddValidModel( "Suit_6a", "models/player/Suits/male_06_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_6a", "models/player/Suits/male_06_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_6b", "models/player/Suits/male_06_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_6b", "models/player/Suits/male_06_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_6c", "models/player/Suits/male_06_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_6c", "models/player/Suits/male_06_open.mdl" )
player_manager.AddValidModel( "Suit_6d", "models/player/Suits/male_06_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_6d", "models/player/Suits/male_06_open_tie.mdl" )
player_manager.AddValidModel( "Suit_6e", "models/player/Suits/male_06_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_6e", "models/player/Suits/male_06_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_6f", "models/player/Suits/male_06_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Suit_6f", "models/player/Suits/male_06_shirt.mdl" )
player_manager.AddValidModel( "Suit_6g", "models/player/Suits/male_06_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_6g", "models/player/Suits/male_06_shirt_tie.mdl" )
player_manager.AddValidModel( "Suit_7a", "models/player/Suits/male_07_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_7a", "models/player/Suits/male_07_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_7b", "models/player/Suits/male_07_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_7b", "models/player/Suits/male_07_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_7c", "models/player/Suits/male_07_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_7c", "models/player/Suits/male_07_open.mdl" )
player_manager.AddValidModel( "Suit_7d", "models/player/Suits/male_07_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_7d", "models/player/Suits/male_07_open_tie.mdl" )
player_manager.AddValidModel( "Suit_7e", "models/player/Suits/male_07_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_7e", "models/player/Suits/male_07_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_7f", "models/player/Suits/male_07_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Suit_7f", "models/player/Suits/male_07_shirt.mdl" )
player_manager.AddValidModel( "Suit_7g", "models/player/Suits/male_07_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_7g", "models/player/Suits/male_07_shirt_tie.mdl" )
player_manager.AddValidModel( "Suit_8a", "models/player/Suits/male_08_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_8a", "models/player/Suits/male_08_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_8b", "models/player/Suits/male_08_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_8b", "models/player/Suits/male_08_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_8c", "models/player/Suits/male_08_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_8c", "models/player/Suits/male_08_open.mdl" )
player_manager.AddValidModel( "Suit_8d", "models/player/Suits/male_08_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_8d", "models/player/Suits/male_08_open_tie.mdl" )
player_manager.AddValidModel( "Suit_8e", "models/player/Suits/male_08_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_8e", "models/player/Suits/male_08_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_8f", "models/player/Suits/male_08_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Suit_8f", "models/player/Suits/male_08_shirt.mdl" )
player_manager.AddValidModel( "Suit_8g", "models/player/Suits/male_08_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_8g", "models/player/Suits/male_08_shirt_tie.mdl" )
player_manager.AddValidModel( "Suit_9a", "models/player/Suits/male_09_closed_coat_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_9a", "models/player/Suits/male_09_closed_coat_tie.mdl" )
player_manager.AddValidModel( "Suit_9b", "models/player/Suits/male_09_closed_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_9b", "models/player/Suits/male_09_closed_tie.mdl" )
player_manager.AddValidModel( "Suit_9c", "models/player/Suits/male_09_open.mdl" )
list.Set( "PlayerOptionsModel", "Suit_9c", "models/player/Suits/male_09_open.mdl" )
player_manager.AddValidModel( "Suit_9d", "models/player/Suits/male_09_open_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_9d", "models/player/Suits/male_09_open_tie.mdl" )
player_manager.AddValidModel( "Suit_9e", "models/player/Suits/male_09_open_waistcoat.mdl" )
list.Set( "PlayerOptionsModel", "Suit_9e", "models/player/Suits/male_09_open_waistcoat.mdl" )
player_manager.AddValidModel( "Suit_9f", "models/player/Suits/male_09_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Suit_9f", "models/player/Suits/male_09_shirt.mdl" )
player_manager.AddValidModel( "Suit_9g", "models/player/Suits/male_09_shirt_tie.mdl" )
list.Set( "PlayerOptionsModel", "Suit_9g", "models/player/Suits/male_09_shirt_tie.mdl" )
player_manager.AddValidModel( "Robber_1", "models/player/Suits/robber_open.mdl" )
list.Set( "PlayerOptionsModel", "Robber_1", "models/player/Suits/robber_open.mdl" )
player_manager.AddValidModel( "Robber_2", "models/player/Suits/robber_shirt.mdl" )
list.Set( "PlayerOptionsModel", "Robber_2", "models/player/Suits/robber_shirt.mdl" )
player_manager.AddValidModel( "Robber_3", "models/player/Suits/robber_shirt_2.mdl" )
list.Set( "PlayerOptionsModel", "Robber_3", "models/player/Suits/robber_shirt_2.mdl" )
player_manager.AddValidModel( "Robber_4", "models/player/Suits/robber_tie.mdl" )
list.Set( "PlayerOptionsModel", "Robber_4", "models/player/Suits/robber_tie.mdl" )
player_manager.AddValidModel( "Robber_5", "models/player/Suits/robber_tuckedtie.mdl" )
list.Set( "PlayerOptionsModel", "Robber_5", "models/player/Suits/robber_tuckedtie.mdl" )
