--leak by matveicher
--vk group - https://vk.com/codespill
--steam - https://steamcommunity.com/profiles/76561198968457747/
--ds server - https://discord.gg/7XaRzQSZ45
--ds - matveicher

-- To-do, add A LOT more of these
-- перявядите ето нормально, а то ощибок много
term.Add('JobNeedZombie', 'Ты должен быть зараженным!')
term.Add('UmbHasDied', 'Управляющий амбреллы мёртв!')
term.Add('BossHasDied', 'Глава мафии мёртв!')
----------------
term.Add('DataNotLoaded', 'СЛЁТ БАЗЫ ДАННЫХ!')
term.Add('PleaseWaitX', 'Пожалуйста, подождите # секунд чтобы сделать это.')
term.Add('+Money', '+₽#')
term.Add('-Money', '-₽#')
term.Add('Npckill', 'Вы убили npc')
term.Add('InvalidArg', 'Недействительный аргумент.')
term.Add('CantFindPlayer', 'Невозможно найти #.')
term.Add('CannotAfford', 'Вы не можете позволить себе это!')
term.Add('NeedVIP', 'Вам нужен статус VIP.')
term.Add('JobNeedsPlaytime', 'Вам нужно # час(ов) игрового времени или статус VIP для этой работы!')
term.Add('NeedToWait', 'Нужно подождать # секунд чтобы сделать это!')
term.Add('ChangeJob', '# стал #.')
term.Add('CannotChangeJob', 'Вы не можете сменить работу в течении #!')
term.Add('ChangeName', '# сменил ролевое имя на #')
term.Add('Payday', 'Зарплата! Вы получили ₽#.')
term.Add('PaydayTax', 'Зарплата! Вы получили ₽# - ₽# налог.')
term.Add('PayDayUnemployed', 'Вы безработный и вы не получаете зарплату!')
term.Add('PayDayMissed', 'Зарплата пропущена! (Вы под арестом)')
term.Add('PayDayCanAfford', 'Вы не смогли уплатить налоги! Ваша собственность отобрана у вас!')
term.Add('NotAllowedInSpawn', '# недопустимо на спавне!')
-- term.Add('LostKarma', 'You have lost # karma for #!')
-- term.Add('LostKarmaNR', 'You have lost # karma.')
-- term.Add('LostKarmaDrugs', 'You have lost # karma for doing drugs.')
term.Add('SpawnPropsSoFast', 'Пожалуйста, не создавайте пропы так быстро.')
term.Add('RPNameShort', 'RP имя должно быть длиннее # символов.')
term.Add('RPNameLong', 'RP имя должно быть короче # символов.')
term.Add('CannotRPName', 'Вы не можете изменить RP имя.')
term.Add('RPNameUnallowed', 'Это имя содержит недоступные символы (#).')
term.Add('SteamRPNameTaken', 'Ваше Steam-Имя уже используется кем-то, поэтому мы поставили "1" после Вашего имени.')
term.Add('RPNameTaken', 'Это RP имя уже занято')
term.Add('EscapeDemotion', 'Вы попытались избежать увольнения. Хорошая попытка, но вы всё равно были уволены.')
term.Add('PlayerDemoted', '# был уволен.')
term.Add('PlayerNotDemoted', '# не был уволен.')
term.Add('DemotionStarted', '# запустил голосование об увольнении #.')
term.Add('DemotionReason', 'Вам нужно указать причину.')
term.Add('DemoteReasonLong', 'Ваша причина увольнения должна быть длиннее # символов.')
term.Add('DemoteSelf', 'Вы не можете уволить себя.')
term.Add('UnableToDemote', 'Вы не можете голосовать.')
term.Add('ChannelLimit', 'Канал должен быть числом 1-100.')
term.Add('ChannelSet', 'Канал установлен на #.')
term.Add('ChannelNotSet', 'Вы не выставили свой канал!')
term.Add('GiveMoneyLimit', 'Вы не можете передать меньше чем ₽1.')
term.Add('DropMoneyLimit', 'Вы не можете бросить меньше чем ₽1.')
term.Add('ChequeArg1', 'Недействительный аргумент #1: получатель.')
term.Add('ChequeArg2', 'Недействительный аргумент #2: количество.')
term.Add('PlayerGaveCash', '# дал вам #.')
term.Add('YouGaveCash', 'Вы дали # #.')
term.Add('MustLookAtPlayer', 'Вам нужно смотреть на игрока.')

term.Add('HoesProfit', 'Вы получили ₽100 от своих Проституток.')
term.Add('CannotAffordHoe', '# не может себе позволить ваши услуги!')
term.Add('YouCannotAffordHoe', 'Вы не можете позволить себе # услугу!')
term.Add('GetCloser', 'Вы должны быть ближе к своей цели!')
term.Add('YouAreDead', 'Вы мертвы!')
term.Add('NotAHoe', 'Вы не Проститутка.')
term.Add('NPCsDontFuck', 'Вы не можете трахать NPC.')
term.Add('TargetFrozen', 'Ваша цель заморожена.')
term.Add('WaitingForAnswer', 'В ожидании ответа.')
term.Add('TargetWontFuck', 'Ваша цель не хочет трахаться.')
term.Add('TargetTooFar', 'Ваша цель слишком далеко.')
term.Add('HoeTooFar', 'Ваша Проститутка слишком далеко.')
term.Add('+FuckCostPimp', '+ ₽# - 100 (Pimp\'s cut)')

term.Add('Warranted', '# взял ордер\nПричина: #\nОрдер на: #.')
term.Add('Wanted', '# в розыске\nПричина: #\nВыдал ордер: #.')
term.Add('Arrested', '# был арестован.')
term.Add('UnArrested', '# выпущен из тюрьмы.')
term.Add('Cuff', '# надел на вас наручники.')
term.Add('UnCuff', '# снял наручники.')

term.Add('Mask', 'Вы одели маску! Она будет действовать 300 сек!')

term.Add('DoorLocked', 'Закрыто!')
term.Add('DoorUnlocked', 'Открыто!')
term.Add('TeamCannotOwnDoor', 'Эта профессия не может владеть дверями.')
term.Add('MaxDoors', 'Вы достигли лимита дверей!')
term.Add('DoorBought', 'Вы купили # за #.')
term.Add('DoorOwnerAdded', '# был добавлен в Вашу дверь.')
term.Add('DoorOwnerAddedYou', '# добавил Вас в свою дверь.')
term.Add('DoorOwnerRemoved', '# был удалён из Вашей двери.')
term.Add('DoorOwnerRemovedYou', '# удалил из своей двери.')
term.Add('DoorSold', 'Вы продали # за #.')
term.Add('DoorTitleSet', 'Название изменено.')
term.Add('OrgDoorEnabled', 'Владение организации разрешено.')
term.Add('OrgDoorDisabled', 'Владение организации запрещено.')
term.Add('NoDoors', 'У вас нет дверей для продажи.')
term.Add('DoorsSold', 'Вы продали # дверей за #.')

-- term.Add('EventEnded', '# Ивент закончился.')

term.Add('OrgDisbanded', '# был распущен!')
term.Add('OrgPlayerKicked', '# кикнут из организации #.')
term.Add('OrgPlayerYoureKicked', 'Вы были кикнуты из организации #.')
term.Add('OrgMustLeaveFirst', 'Вам нужно покинуть организацию чтобы создать новую.')
term.Add('OrgNameShort', 'Пожалуйста, сделайте название своей организации длиннее чем 2 буквы.')
term.Add('OrgNameLong', 'Пожалуйста, сделайте название своей организации короче чем чем 20 букв.')
term.Add('OrgNameTaken', 'Это имя уже занято. Пожалуйста выберите другое!')
term.Add('OrgCannotAffort', 'Вы не можете позволить себе создать организацию.')
term.Add('OrgCreated', 'Вы успешно создали свою организацию.')
term.Add('OrgMOTDChanged', 'Вы изменили вашу организацию MoTD.')
term.Add('OrgColorChanged', 'Вы изменили цвет организации.')
term.Add('OrgPlayerQuit', '# вышел из #!')
term.Add('OrgMemberLimit', 'Вы достигли максимального количество # членов в организации!')
term.Add('OrgMemberJoined', '# присоединился к #.')

term.Add('MustBeMayorSetLaws', 'Вы должны быть мэром, чтобы устанавливать законы!')
term.Add('MustBeMayorResetLaws', 'Вы должны быть мэром, чтобы удалить законы!')
term.Add('LotteryTax', 'Вы получили с лотереи #.')
term.Add('LotteryWinner', '# выиграл # в лотерее!')
term.Add('NoLottery', 'Никто не участвовал в лотерее, поэтому ваши деньги были возвращены.')
term.Add('NoLotteryTax', 'Вы получили с лотереи ₽0, потому что никто не участвовал в лотерее.')
term.Add('NotInLottery', 'Вы не участвует в лотерее.')
term.Add('InLottery', 'Вы участвуете в лотерее за #.')
term.Add('NoLotteryAll', 'Никто не участвовал в лотерее.')
term.Add('CannotLottery', 'Вы не можете начать лотерею прямо сейчас.')
term.Add('LottoCooldown', 'Пожалуйста, подождите # секунд, чтобы начать новую лотерею.')
term.Add('LottoCost', 'Пожалуйста, установ цену на вход (₽#-₽#).')
term.Add('LotteryStarted', 'Лотерея началась!')

term.Add('CannotLockdown', 'Комендантский час сейчас недоступен.')
term.Add('LockdownStarted', 'Мэр объявил комендантский час, возвращайтесь по домам!')
term.Add('CannotUnlockdown', 'Вы не можете запустить комендантский час сейчас.')
term.Add('LockdownEnded', 'Комендатский час отменён.')

term.Add('WarrantExpired', 'Ордер на обыск # истёк.')
term.Add('WantedPlayerNotFound', '# не найден!')
term.Add('PlayerAlreadyWanted', '# yже разыскивается полицией!')
term.Add('PlayerAlreadyWarranted', '# yже есть ордер!')
term.Add('PlayerNotWanted', '# не разыскивается полицией!')
term.Add('PlayerNotWarranted', 'На # нет ордера!')
term.Add('WarrantRequestAcc', 'Ваш ордер одобрен.')
term.Add('WarrantRequestDen', 'Ваш ордер был отклонён.')

term.Add('HitComplete', 'Заказ на # выполнен.')
term.Add('YourHitComplete', 'Вас убил наемный убийца.')
term.Add('HitTargetInvalid', 'Вы должны выбрать правильную цель!')
term.Add('CantHitYourself', 'Вы не можете заказать себя!')
term.Add('CantHitHitman', 'Вы не можете заказать киллера!')
term.Add('CantPlaceHit', 'Вы не можете заказывать')
term.Add('HitPriceLimit', 'Цена должна быть от ₽1,000 до ₽50,000.')
term.Add('HitTimer', 'Вы не можете нанести удар в течении # секунд.')
term.Add('MultiHit', 'Вы не можете убивать дважды одного и того же человека!')
term.Add('BountyIncrease', 'Вы увеличили вознаграждение за # на #.')
term.Add('HitPlaced', 'Вы сделали заказ на # за #.')
term.Add('HitmanFailed', 'Вы не выполнили заказ.')

term.Add('GamblingMachinePlayerCannotAfford', 'You cannot afford to play this # machine!')
term.Add('GamblingMachineHouseCannotAfford', 'You cannot afford your # machine! It is now out of service.')
term.Add('GamblingMachineOwnerCannotAfford', 'The owner of this # machine can no longer afford to operate. It is now out of service.')
term.Add('GamblingMachineInService', 'Your # machine is now in service.')
term.Add('GamblingMachineIOutService', 'Your # machine is now out of service.')

term.Add('5050PlayerWin', 'You won # playing FiftyFifty!')
term.Add('5050PlayerLose', 'You lost # playing FiftyFifty!')
term.Add('5050Tie', 'You tied and got your money back.')

term.Add('BasicSlotsPlayerWin', 'You won # playing Slots!')
term.Add('BasicSlotsPlayerLose', 'You lost # playing Slots!')

term.Add('SpinWheelPlayerWin', 'You won # playing Spin Wheel!')
term.Add('SpinWheelPlayerLose', 'You lost # playing Spin Wheel!')

term.Add('RoulettePlayerWin', 'You won # playing Roulette!')
term.Add('RoulettePlayerLose', 'You lost # playing Roulette')

term.Add('EmployeeChangedJob', 'Ваш наниматель изменил работу!')
term.Add('EmployeeChangedJobYou', 'Ваш контракт был отменён потому, что вы сменили работу!')
term.Add('EmployeeDied', 'Ваш контракт был отменён потому что, Наёмник - умер!')
term.Add('EmployeeDiedYou', 'Ваш контракт был отменён потому что, Вы - умерли!')
term.Add('EmployerDied', 'Ваш наниматель умер!')
term.Add('EmployerDiedYou', 'Ваш работник уволен потому, что вы умерли.')
term.Add('EmployeeLeft', 'Ваша цель отключилась!')
term.Add('EmployerLeft', 'Ваш наниматель отключился!')
term.Add('PlayerNotHirable', '# не может быть нанят.')
term.Add('EmployeeTriedEmploying', 'В данный момент Вы ищете работу. Вы не можете нанять рабочего !')
term.Add('HasEmployee', 'Вы уже наёмный работник!')
term.Add('AlreadyEmployed', 'Вы уже нанят!')
term.Add('CannotAffordEmployee', 'Вы не можете нанять!')
term.Add('EmployRequestSent', '# отправил Вам запрос на найм.')
term.Add('EmployRequestSents', 'Отправлен запрос на найм #.')
term.Add('YouHired', 'Вы наняли # за #.')
term.Add('YouAreHired', '# нанял Вас за #.')
term.Add('EmployRequestDen', '# отменил вашу заявку на работу.')
term.Add('EmployeeFired', 'Вы уволены #.')
term.Add('EmployeeFiredYou', '# Уволил вас!')
term.Add('EmployeeQuit', '# Вышел с работы вместе с вами!')
term.Add('EmployeeQuitYou', 'Вы ушли с работы #.')

term.Add('CannotTool', 'Недостаточно прав использовать "#" инструмент!')
term.Add('DupeRestrictedEnts', 'Вы не можете создавать дупликаты этих объектов!')
term.Add('WhitelistFull', ' Белый Список полон #/750')
term.Add('CacheFull', 'Модель Кэша заполнена #/100!')
term.Add('PropWhitelisted', '# добавлен в Белый Список #.')
term.Add('PropBlacklisted', '# был помещен в Черный Список #.')
term.Add('PPTargNotFound', 'Цель не найдена !')
term.Add('UnsharedPropsYou', 'Вы отменили доступ к своим пропам для #.')
term.Add('UnsharedProps', '# отменил вам доступ к своим пропам.')
term.Add('SharedPropsYou', 'Вы открыли доступ к своим пропам для  #.')
term.Add('SharedProps', '# Предоставил доступ к своим пропам для вас.')
term.Add('PPGroupSet', '# был добавлен в группу # by #.')
term.Add('PropNotWhitelisted', '# не в вайтлисте!')

term.Add('NoPMResponder', 'Там никого нет чтобы ответить')
term.Add('CannotDestroyWeapon', 'Вы не можете уничтожить это оружие!')

term.Add('YourEntDestroyed', 'Ваша # было уничтожено!')
term.Add('InvalidURL', 'Не правильный URL!')
term.Add('VideoFailed', 'Не удалось загрузить видео: #.')
term.Add('FoodLimitReached', 'Вы достигли лимита еды!')
term.Add('BoughtFoodProduction', 'Вы заплатили # за продукты.')
term.Add('SoldFoodNoProf', 'Вы продали еду и не получили денег, но ничего не зарабатываете.')
term.Add('SoldFood', 'Вы продали еду и заработали # и получили.')
term.Add('BoughtFood', 'Вы приобрели еду за #.')
term.Add('ThereIsACook', 'Есть повар. Вы не можете это сделать!')
term.Add('EmptyShipment', 'Там нет товаров.')

-- term.Add('GCMessageLimit', 'Ваше сообщение должно быть больше чем 1 символ!')

term.Add('CantSuicideJail', 'Вы не можете покончить жизнь самоубийством в тюрьме.')
term.Add('CantSuicideWanted', 'Вы не можете покончить жизнь самоубийством пока вы в розыске .')
term.Add('CantSuicideFrozen', 'Вы не можете покончить жизнь самоубийством пока вы freeze.')
term.Add('CantSuicideLiveFor', 'Ты слишком мал чтобы делать это!')
term.Add('YouSuicided', 'Ты позор для своей семьи!')

term.Add('CantPurchaseUpgrade', 'Вы не можете купить это. #')

term.Add('RPItemBought', 'Вы купили # за #.')
term.Add('RPItemBoughtLimit', 'Вы купили #/# # за #.')

term.Add('CantAdminCleanup', 'Вы не можете использовать очистку сервера как Admin!')

term.Add('MayorHasDied', 'Мэр мёртв!')
term.Add('YouWereBailed', '# заплатил за вас залог!')

term.Add('ArmorLabProfit', 'Вы получили ₽# с раздатчика брони.')
term.Add('BoughtArmor', 'Вы купили броню за ₽#.')
term.Add('ArmorLabExploded', 'Вашь раздатчик брони взорвался!')

term.Add('ChequeFound', 'Вы нашли # в чеке, выписанном вам от #.')
term.Add('ChequeMadeTo', 'Этот чек выписан #.')
term.Add('ChequeTorn', 'Вы разорвали чек.')
term.Add('MoneyFound', 'Вы нашли ₽#!')

term.Add('MustBeHobo', 'Ты должен быть бомжом чтобы обыскивать мусорки!')
term.Add('AlreadyDisguised', 'Вы уже замаскированы!')
term.Add('GunLicenseActive', 'Вы активировали лицензию на оружие.')
-- term.Add('YouGotAIDS', 'Вы заразились спидом и скоро умрете.')
-- term.Add('YouGotHerpes', 'You have contracted herpes from an exposed needle.')
-- term.Add('STDCured', 'Вы вылечили свои заболевание, передающиеся половым путем.')
term.Add('NowDisguised', 'Вы замаскированы как #.')
term.Add('NowDisguisedTime', 'Вы замаскированы на # минут #.')
term.Add('DisguiseWorn', 'Ваша маскировка закончилась.')
term.Add('DisguiseLimit', 'Вы не можете маскироваться ещё # минут.')

 term.Add('MedLabProfit', 'Вы получили ₽# с раздатчика здоровья.')
 term.Add('BoughtHealth', 'Вы купили здоровья за ₽#.')
 term.Add('MedLabExploded', 'Вашь раздатчик здоровья  взорвался!')

term.Add('KeypadControlsX', 'This keypad controls # entities.')
term.Add('EntityControlledByX', 'This entity is controlled by # keypads.')

term.Add('VoteAlone', 'Вы выиграли голосование так как вы один на сервере.')
term.Add('BannedFromJob', 'В настоящее время эта работа недоступна для вас.')
term.Add('VotedTooSoon', 'Пожалуйста, подождите # секунд чтобы начать голосование.')
term.Add('AlreadyThisJob', 'Вы уже на этой работе!')
term.Add('JobLimit', 'Лимит исчерпан.')
term.Add('RegisteredForVote', 'Вы зарегистрированы на предстоящие выборы!')
term.Add('AlreadyVoting', 'Выборы уже начались. Вы опоздали!')
term.Add('JobNeedsAdmin', 'Вы должны быть moderator+ для этой работы.')
term.Add('JobNeedsSA', 'Вы должны быть SA+ для этой работы.')
term.Add('JobNeedsBanned', 'Ты должен быть забанен на сервере чтобы получить этот класс')
term.Add('IncorrectJob', 'Неправильная работа для этого!')
term.Add('VoteStarted', 'Голосование создано.')
term.Add('CannotJob', 'Вы не можете изменить работу прямо сейчас.')
term.Add('JobLenShort', 'Название работы должно быть больше чем # буква.')
term.Add('JobLenLong', 'Название работы должно быть меньше чем  # букв.')

term.Add('CannotPurchaseItem', 'Вы не допущены к покупке этого предмета.')
term.Add('ItemLimit', 'Вы достигли # лимит.')
term.Add('ItemUnavailable', 'Эта вещь недоступна.')
term.Add('UnableToItem', 'Вы не в состоянии купить эту вещь.')
term.Add('ShipmentCooldown', 'Подождите прежде чем спавнить товар.')

-- term.Add('MedicExists', 'You cannot buy health because there are medics.')
-- term.Add('HealthIsFull', 'Your health is full already!')

term.Add('CannotDropWeapon', 'Нельзя выбросить это оружие!')
term.Add('LookAtEntity', 'Вы должны смотреть на предмет!')
term.Add('CannotSetPrice', 'Вы не можете установить цену на этот предмет!')

 term.Add('AnalProlapse', 'You have overexerted your anus and died from anal prolapse.')
 term.Add('NoMorePoo', 'You have no more poo left!')
 term.Add('NotARapist', 'Вы не Насильник.')
 term.Add('RapeNPC', 'Вы не можете изнасиловать NPC.')
 term.Add('RapeFailed', 'Изнасилование не удалось!')
 term.Add('RapeAttempted', 'Кто-то попытался попасть в ваш анус.')
 term.Add('Raped', 'Вы проник в анус #.')
 term.Add('YouAreRaped', 'Кто-то проник в ваш анус.')
 term.Add('AnalProlapseShort', 'Вы умерли от анального пролапса.')
 term.Add('DickFellOff', 'Ваш член упал.')

term.Add('CannotVote', 'Вы не можете голосовать!')
term.Add('CantDoThis', 'Вы не можете сделать это.')
term.Add('BaitingRule', 'Это не по правилам.')
term.Add('FoundNothing', 'Вы ничего не нашли.')
term.Add('RobberyAttempt', 'Вы почувствовали легкое движение в кармане.')
term.Add('RobberyFailed', 'Ограбление не удалось!')
term.Add('YouRobbed', 'Вы украли ₽#!')
term.Add('YouAreRobbed', 'Ваш карман чувствует себя легче.')

term.Add('NoteUpdated', 'Текст обновлен.')
term.Add('USENote', 'Нажмите USE, чтобы отредактировать текст.')

term.Add('OrgYouAreStuck', 'Вы застряли! >:)')
term.Add('OrgYourRank', '# установил ваш ранг \'#\'.')
term.Add('OrgSetRank', '# добавлен \'#\'.')
term.Add('OrgUnknownRank', 'неизвестный ранг \'#\'.')
term.Add('OrgRankRename', 'Ранг \'#\' переименован в \'#\'.')
term.Add('OrgReorderLimit', 'Вы не можете изменить Высший и Низший ранги.')
term.Add('OrgRankUpdated', 'Ранг \'#\' обновлен.')
term.Add('OrgMaxRanks', 'Максимальный ранг достигнут.')
term.Add('OrgRankCreated', 'Ранг \'#\' Создан.')
term.Add('OrgDeleteLimit', 'Вы не можете удалить высший и низший ранг.')
term.Add('OrgRankDelete', 'Ранг \'#\' удалён.')
term.Add('OrgBannerUpdated', 'Банер обновлён.')

term.Add('FadeDoorCreated', 'Fading door создан.')
term.Add('FadeDoorCreatedExtra', 'Fading door создан.Теперь нажмите правую кнопку мыши еще раз, чтобы поместить Keypad')
term.Add('InvalidPassword', 'Неверный пароль!')
-- term.Add('KeypadHoldLength', 'Длина удержания должна быть не менее # секунд.')
term.Add('KeypadCreated', 'Keypad создан.')
term.Add('NoCollided', 'Коллизия выключена.')
term.Add('Collided', 'Коллизия включена.')

-- Sandbox
term.Add('SboxPropLimit', 'Вы достигли лимита пропов!')
term.Add('SboxXLimit', 'Вы достигли # лимит!')
term.Add('SboxSpawned', 'Создано #/# #.')

-- Entities folder
-- term.Add('ArcadeMachineUse', 'Get ready to play!')
term.Add('PlayerNotInJail', '# не в тюрьме.')
-- term.Add('PlayerFuckedBailing', 'You dumbass, the cops are hot on your tail now!')
 term.Add('PlayerBailedPlayer', 'Вы заплатили залог за #.')
term.Add('PlayerTookDonationBox', 'Вы взяли #.')
term.Add('YouDontOwnThis', 'Вы не являетесь владельцем этого!')
term.Add('PlayerReceivedDonationBox', 'Кто-то пожертвовал вам #.')
-- term.Add('DrugLabExploded', 'Ваша нарко-лаборатория взорвалась!')
term.Add('PlayerNotWanted', 'Этот игрок не разыскивается!')
term.Add('PlayerTookMoneyBasket', 'Вы взяли #.')
term.Add('PrinterIsFull', 'Принтер переполнен чернилами!')
term.Add('PrinterRefilled', 'Вы купили чернил на #.')
term.Add('PrinterExploded', 'Ваш денежный принтер взорвался!')
term.Add('PlayerSoldDrugs', 'Вы продали # за #.')

-- Weapons folder
term.Add('ArrestBatonBonus', 'Вы получили # за уничтожение нелегального предмета.')
term.Add('ArrestBatonArrested', '# арестовал вас.')
term.Add('ArrestBatonYouArrested', 'Вы арестовали #.')
term.Add('PlayerRangDoorbell', 'Кто-то позвонил в ваш звонок.')
term.Add('KeysCooldown', 'Пожалуйста, подождите прежде чем закрывать дверь.')
term.Add('UnarrestBatonTarg', '# выпустил вас.')
term.Add('UnarrestBatonOwn', 'Вы выпустили #.')
term.Add('RiotShieldInSpawn', 'Браток тикай со спавно со своим shit\'om')

term.Add('HatPurchased', 'Вы купили # за #.')
term.Add('HatEquipped', 'Шапка надета!')
term.Add('HatRemoved', 'Шапка снята!')

term.Add('NelzaAdmina', 'Вы не можете замаскироваться за Администратора!')

-- term.Add('BURGHungerImmune', 'You\'re immune to hunger until you die, now!')
-- term.Add('BURGNotPeople', 'Silly burger, burgers aren\'t people!')

--leak by matveicher
--vk group - https://vk.com/codespill
--steam - https://steamcommunity.com/profiles/76561198968457747/
--ds server - https://discord.gg/7XaRzQSZ45
--ds - matveicher
