
//Category Titles
tfa.smsettings.ww2k.server=COD WW2 Kabyi Serverside
tfa.smsettings.ww2k.client=COD WW2 Kabyi Clientside

//Help Title Text
tfa.settings.ww2k.misc=Misc Settings 
tfa.settings.ww2k.flame=Flamethrower Settings

//Flamethrower Settings
tfa.svsettings.ww2k.flameregen=Flamethrower Ammo Regen
tfa.svsettings.ww2k.regenrate=Regen Delay
tfa.svsettings.ww2k.regenratepap=Regen Delay PaP

//Client Settings
tfa.clsettings.ww2k.dlight=Enable DLights
