if SERVER then
    -- ЛИЧНЫЕ МОДЕЛИ 28.06
    resource.AddWorkshop("3742180095")
    resource.AddWorkshop("3418985959")
    resource.AddWorkshop("3416401978")
    resource.AddWorkshop("3415224998")
    resource.AddWorkshop("3413929345")
    resource.AddWorkshop("2829029524")
    resource.AddWorkshop("3697577840")
    resource.AddWorkshop("3698672899")
    resource.AddWorkshop("3416550284")
    
    
    resource.AddWorkshop("3698615604") -- мэр
    resource.AddWorkshop("3311770844 ") -- админ
    
    resource.AddWorkshop( "617364029" )
    resource.AddWorkshop( "204120003" )
    resource.AddWorkshop( "214368962" )
    resource.AddWorkshop( "323409288" )
    resource.AddWorkshop( "238499436" )
    resource.AddWorkshop( "323393207" )
    resource.AddWorkshop( "734781319" )
    resource.AddWorkshop( "906408930" )
    resource.AddWorkshop( "738724607" )
    resource.AddWorkshop( "2983611653" )
    resource.AddWorkshop( "1182053993" )
    resource.AddWorkshop( "677129372" )
    resource.AddWorkshop( "608936011" )
    resource.AddWorkshop( "579592077" )
    resource.AddWorkshop( "107411755" )
    resource.AddWorkshop( "1170760871" )
    resource.AddWorkshop( "412149725" )
    resource.AddWorkshop( "597440322" )
    resource.AddWorkshop( "213276429" )
    resource.AddWorkshop( "1843708002" )
    resource.AddWorkshop( "226935476" )
    resource.AddWorkshop( "810090879" )
    resource.AddWorkshop( "1700547049" )
    resource.AddWorkshop( "775344741" )
    resource.AddWorkshop( "1712135857" )
    resource.AddWorkshop( "1493279443" )
    resource.AddWorkshop( "794609277" )
    resource.AddWorkshop( "3086031154" )
    resource.AddWorkshop( "3745003429" )
    resource.AddWorkshop( "2907866695" )
    resource.AddWorkshop( "3003893737" )
    resource.AddWorkshop( "3337860652" )
    resource.AddWorkshop( "3743221782" )
    resource.AddWorkshop( "3036509178" )

    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/body m.vmt")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/body.vmt")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/body_d.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/body_e.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/body_n.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/hair m.vmt")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/hair.vmt")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/hair_d.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/hair_e.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/hair_n.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/head m.vmt")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/head.vmt")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/head_d.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/head_e.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/head_lights.vtf")
    resource.AddFile("materials/models/MrShlapa/Fortnite/Characters/Midas/head_n.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/eye_l.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/eye_r.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/mi_dorsaldance_body.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/mi_dorsaldance_faceacc.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/mi_dorsaldance_head.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_body_d.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_body_m.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_body_n.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_eye.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_faceacc_d.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_faceacc_m.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_faceacc_n.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_head_d.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_head_m.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/Safety_First_Steve/t_dorsaldance_head_n.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/eye_l.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/eye_r.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/mi_dorsaldance_body.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/mi_dorsaldance_faceacc.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/mi_dorsaldance_head.vmt")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_body_d.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_body_m.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_body_n.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_eye.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_faceacc_d.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_faceacc_m.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_faceacc_n.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_head_d.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_head_m.vtf")
    resource.AddFile("materials/models/arctic0ne/fortnite/characters/safety_first_steve/t_dorsaldance_head_n.vtf")
    resource.AddFile("materials/models/arctic0ne/shared/cubemap_eyes.vtf")
    resource.AddFile("materials/models/arctic0ne/shared/green.vtf")
    resource.AddFile("materials/models/arctic0ne/shared/lightwarp_soft_white.vtf")
    resource.AddFile("materials/models/fortnite/plague/lens.vtf")
    resource.AddFile("materials/models/fortnite/plague/m_med_plague_body.vmt")
    resource.AddFile("materials/models/fortnite/plague/m_med_plague_glass.vmt")
    resource.AddFile("materials/models/fortnite/plague/m_med_plague_head.vmt")
    resource.AddFile("materials/models/fortnite/plague/m_med_plague_head_green.vmt")
    resource.AddFile("materials/models/fortnite/plague/n.vtf")
    resource.AddFile("materials/models/fortnite/plague/t_m_med_plague_body_d.vtf")
    resource.AddFile("materials/models/fortnite/plague/t_m_med_plague_body_n.vtf")
    resource.AddFile("materials/models/fortnite/plague/t_m_med_plague_head_d.vtf")
    resource.AddFile("materials/models/fortnite/plague/t_m_med_plague_head_d_green.vtf")
    resource.AddFile("materials/models/fortnite/plague/t_m_med_plague_head_e.vtf")
    resource.AddFile("materials/models/fortnite/plague/t_m_med_plague_head_n.vtf")
    resource.AddFile("materials/models/fortnite/plague/white.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/body m.vmt")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/body.vmt")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/body_d.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/body_e.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/body_n.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/hair m.vmt")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/hair.vmt")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/hair_d.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/hair_e.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/hair_n.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/head m.vmt")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/head.vmt")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/head_d.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/head_e.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/head_lights.vtf")
    resource.AddFile("materials/models/mrshlapa/fortnite/characters/midas/head_n.vtf")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_body.vmt")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_body.vtf")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_body_normal.vtf")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_hair.vmt")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_hair.vtf")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_hair_normal.vtf")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_head.vmt")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_head.vtf")
    resource.AddFile("materials/models/player/billy_fn/billy_fn_head_normal.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_acc.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_acc.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_acc_normal.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_accb.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_accb.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_accg.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_accg.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_accw.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_accw.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_body.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_body.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_body_normal.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_bodyb.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_bodyb.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_bodyg.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_bodyg.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_bodyw.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_bodyw.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_glass.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_glassb.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_glassb.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_glassg.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_glassw.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_glassw.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_head.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_head.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_head_normal.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_headb.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_headb.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_headg.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_headg.vtf")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_headw.vmt")
    resource.AddFile("materials/models/player/doom_fn/doom_fn_headw.vtf")
    resource.AddFile("materials/models/player/jack_fn/jack_fn_body.vmt")
    resource.AddFile("materials/models/player/jack_fn/jack_fn_body.vtf")
    resource.AddFile("materials/models/player/jack_fn/jack_fn_body_normal.vtf")
    resource.AddFile("materials/models/player/jack_fn/jack_fn_head.vmt")
    resource.AddFile("materials/models/player/jack_fn/jack_fn_head.vtf")
    resource.AddFile("materials/models/player/jack_fn/jack_fn_head_normal.vtf")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_body.vmt")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_body.vtf")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_body_normal.vtf")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_head.vmt")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_head.vtf")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_head_glow.vmt")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_head_glow.vtf")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_head_glow_fx.vtf")
    resource.AddFile("materials/models/player/pumpking_fn/pumpking_fn_head_normal.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_alpha.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_alpha.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_body.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_body.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_drawers.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_drawers.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_face.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_face.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_hair.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_hair.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_tops.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica/ncc_tops.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_alpha.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_alpha.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_body.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_body.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_drawers.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_drawers.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_face.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_face.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_hair.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_hair.vtf")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_tops.vmt")
    resource.AddFile("materials/models/sheepylord/Nochica_normal/ncc_tops.vtf")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_alpha.vmt")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_alpha.vtf")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_body.vmt")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_body.vtf")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_drawers.vmt")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_drawers.vtf")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_face.vmt")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_face.vtf")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_hair.vmt")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_hair.vtf")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_tops.vmt")
    resource.AddFile("materials/models/sheepylord/nochica/ncc_tops.vtf")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_alpha.vmt")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_alpha.vtf")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_body.vmt")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_body.vtf")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_drawers.vmt")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_drawers.vtf")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_face.vmt")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_face.vtf")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_hair.vmt")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_hair.vtf")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_tops.vmt")
    resource.AddFile("materials/models/sheepylord/nochica_normal/ncc_tops.vtf")
    resource.AddFile("materials/models/zhennywhenny/PhineasAndFerb/mi_brawngraze_body.vmt")
    resource.AddFile("materials/models/zhennywhenny/PhineasAndFerb/mi_brawngraze_body.vtf")
    resource.AddFile("materials/models/zhennywhenny/PhineasAndFerb/mi_brawngraze_faceacc.vmt")
    resource.AddFile("materials/models/zhennywhenny/PhineasAndFerb/mi_brawngraze_faceacc.vtf")
    resource.AddFile("materials/models/zhennywhenny/PhineasAndFerb/mi_brawngraze_head.vmt")
    resource.AddFile("materials/models/zhennywhenny/PhineasAndFerb/mi_brawngraze_head.vtf")
    resource.AddFile("materials/models/zhennywhenny/phineasandferb/mi_brawngraze_body.vmt")
    resource.AddFile("materials/models/zhennywhenny/phineasandferb/mi_brawngraze_body.vtf")
    resource.AddFile("materials/models/zhennywhenny/phineasandferb/mi_brawngraze_faceacc.vmt")
    resource.AddFile("materials/models/zhennywhenny/phineasandferb/mi_brawngraze_faceacc.vtf")
    resource.AddFile("materials/models/zhennywhenny/phineasandferb/mi_brawngraze_head.vmt")
    resource.AddFile("materials/models/zhennywhenny/phineasandferb/mi_brawngraze_head.vtf")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_arms.dx80.vtx")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_arms.dx90.vtx")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_arms.mdl")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_arms.vvd")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_playermodel.dx80.vtx")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_playermodel.dx90.vtx")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_playermodel.mdl")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_playermodel.phy")
    resource.AddFile("models/arctic0ne/fortnite/characters/steve_playermodel.vvd")
    resource.AddFile("models/fortnite/pladue.dx80.vtx")
    resource.AddFile("models/fortnite/pladue.dx90.vtx")
    resource.AddFile("models/fortnite/pladue.mdl")
    resource.AddFile("models/fortnite/pladue.phy")
    resource.AddFile("models/fortnite/pladue.vvd")
    resource.AddFile("models/fortnite/pladue_arms.dx80.vtx")
    resource.AddFile("models/fortnite/pladue_arms.dx90.vtx")
    resource.AddFile("models/fortnite/pladue_arms.mdl")
    resource.AddFile("models/fortnite/pladue_arms.vvd")
    resource.AddFile("models/fortnite/plague.dx80.vtx")
    resource.AddFile("models/fortnite/plague.dx90.vtx")
    resource.AddFile("models/fortnite/plague.mdl")
    resource.AddFile("models/fortnite/plague.phy")
    resource.AddFile("models/fortnite/plague.vvd")
    resource.AddFile("models/fortnite/plague_arms.dx80.vtx")
    resource.AddFile("models/fortnite/plague_arms.dx90.vtx")
    resource.AddFile("models/fortnite/plague_arms.mdl")
    resource.AddFile("models/fortnite/plague_arms.vvd")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm.dx90.vtx")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm.mdl")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm.phy")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm.vvd")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm_arms.dx80.vtx")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm_arms.dx90.vtx")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm_arms.mdl")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm_arms.sw.vtx")
    resource.AddFile("models/mrshlapa/fortnite/characters/midas/midas_pm_arms.vvd")
    resource.AddFile("models/player/billy_fn_pm.dx80.vtx")
    resource.AddFile("models/player/billy_fn_pm.dx90.vtx")
    resource.AddFile("models/player/billy_fn_pm.mdl")
    resource.AddFile("models/player/billy_fn_pm.phy")
    resource.AddFile("models/player/billy_fn_pm.sw.vtx")
    resource.AddFile("models/player/billy_fn_pm.vvd")
    resource.AddFile("models/player/doom_fn_pm.dx80.vtx")
    resource.AddFile("models/player/doom_fn_pm.dx90.vtx")
    resource.AddFile("models/player/doom_fn_pm.mdl")
    resource.AddFile("models/player/doom_fn_pm.phy")
    resource.AddFile("models/player/doom_fn_pm.sw.vtx")
    resource.AddFile("models/player/doom_fn_pm.vvd")
    resource.AddFile("models/player/jack_fn_pm.dx80.vtx")
    resource.AddFile("models/player/jack_fn_pm.dx90.vtx")
    resource.AddFile("models/player/jack_fn_pm.mdl")
    resource.AddFile("models/player/jack_fn_pm.phy")
    resource.AddFile("models/player/jack_fn_pm.sw.vtx")
    resource.AddFile("models/player/jack_fn_pm.vvd")
    resource.AddFile("models/player/pumpking_fn_pm.dx80.vtx")
    resource.AddFile("models/player/pumpking_fn_pm.dx90.vtx")
    resource.AddFile("models/player/pumpking_fn_pm.mdl")
    resource.AddFile("models/player/pumpking_fn_pm.phy")
    resource.AddFile("models/player/pumpking_fn_pm.sw.vtx")
    resource.AddFile("models/player/pumpking_fn_pm.vvd")
    resource.AddFile("models/sheepylord/Nochica/Nochica.dx80.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica.dx90.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica.mdl")
    resource.AddFile("models/sheepylord/Nochica/Nochica.phy")
    resource.AddFile("models/sheepylord/Nochica/Nochica.vvd")
    resource.AddFile("models/sheepylord/Nochica/Nochica_arms.dx80.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_arms.dx90.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_arms.mdl")
    resource.AddFile("models/sheepylord/Nochica/Nochica_arms.vvd")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal.dx80.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal.dx90.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal.mdl")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal.phy")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal.vvd")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_arms.dx80.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_arms.dx90.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_arms.mdl")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_arms.vvd")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_pm.dx80.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_pm.dx90.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_pm.mdl")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_pm.phy")
    resource.AddFile("models/sheepylord/Nochica/Nochica_normal_pm.vvd")
    resource.AddFile("models/sheepylord/Nochica/Nochica_pm.dx80.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_pm.dx90.vtx")
    resource.AddFile("models/sheepylord/Nochica/Nochica_pm.mdl")
    resource.AddFile("models/sheepylord/Nochica/Nochica_pm.phy")
    resource.AddFile("models/sheepylord/Nochica/Nochica_pm.vvd")
    resource.AddFile("models/sheepylord/nochica/nochica.dx80.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica.dx90.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica.mdl")
    resource.AddFile("models/sheepylord/nochica/nochica.phy")
    resource.AddFile("models/sheepylord/nochica/nochica.vvd")
    resource.AddFile("models/sheepylord/nochica/nochica_arms.dx80.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_arms.dx90.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_arms.mdl")
    resource.AddFile("models/sheepylord/nochica/nochica_arms.vvd")
    resource.AddFile("models/sheepylord/nochica/nochica_normal.dx80.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_normal.dx90.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_normal.mdl")
    resource.AddFile("models/sheepylord/nochica/nochica_normal.phy")
    resource.AddFile("models/sheepylord/nochica/nochica_normal.vvd")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_arms.dx80.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_arms.dx90.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_arms.mdl")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_arms.vvd")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_pm.dx80.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_pm.dx90.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_pm.mdl")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_pm.phy")
    resource.AddFile("models/sheepylord/nochica/nochica_normal_pm.vvd")
    resource.AddFile("models/sheepylord/nochica/nochica_pm.dx80.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_pm.dx90.vtx")
    resource.AddFile("models/sheepylord/nochica/nochica_pm.mdl")
    resource.AddFile("models/sheepylord/nochica/nochica_pm.phy")
    resource.AddFile("models/sheepylord/nochica/nochica_pm.vvd")
    resource.AddFile("models/weapons/billy_fn_hands.dx80.vtx")
    resource.AddFile("models/weapons/billy_fn_hands.dx90.vtx")
    resource.AddFile("models/weapons/billy_fn_hands.mdl")
    resource.AddFile("models/weapons/billy_fn_hands.sw.vtx")
    resource.AddFile("models/weapons/billy_fn_hands.vvd")
    resource.AddFile("models/weapons/doom_fn_hands.dx80.vtx")
    resource.AddFile("models/weapons/doom_fn_hands.dx90.vtx")
    resource.AddFile("models/weapons/doom_fn_hands.mdl")
    resource.AddFile("models/weapons/doom_fn_hands.sw.vtx")
    resource.AddFile("models/weapons/doom_fn_hands.vvd")
    resource.AddFile("models/weapons/jack_fn_hands.dx80.vtx")
    resource.AddFile("models/weapons/jack_fn_hands.dx90.vtx")
    resource.AddFile("models/weapons/jack_fn_hands.mdl")
    resource.AddFile("models/weapons/jack_fn_hands.sw.vtx")
    resource.AddFile("models/weapons/jack_fn_hands.vvd")
    resource.AddFile("models/weapons/pumpking_fn_hands.dx80.vtx")
    resource.AddFile("models/weapons/pumpking_fn_hands.dx90.vtx")
    resource.AddFile("models/weapons/pumpking_fn_hands.mdl")
    resource.AddFile("models/weapons/pumpking_fn_hands.sw.vtx")
    resource.AddFile("models/weapons/pumpking_fn_hands.vvd")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_PM.dx80.vtx")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_PM.dx90.vtx")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_PM.mdl")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_PM.phy")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_PM.vvd")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_carms.dx80.vtx")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_carms.dx90.vtx")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_carms.mdl")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/AgentP_carms.vvd")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_carms.dx80.vtx")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_carms.dx90.vtx")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_carms.mdl")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_carms.vvd")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_pm.dx80.vtx")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_pm.dx90.vtx")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_pm.mdl")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_pm.phy")
    resource.AddFile("models/zhennywhenny/PhineasAndFerb/agentp_pm.vvd")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_PM.dx80.vtx")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_PM.dx90.vtx")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_PM.mdl")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_PM.phy")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_PM.vvd")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_carms.dx80.vtx")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_carms.dx90.vtx")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_carms.mdl")
    resource.AddFile("models/zhennywhenny/phineasandferb/AgentP_carms.vvd")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_carms.dx80.vtx")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_carms.dx90.vtx")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_carms.mdl")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_carms.vvd")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_pm.dx80.vtx")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_pm.dx90.vtx")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_pm.mdl")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_pm.phy")
    resource.AddFile("models/zhennywhenny/phineasandferb/agentp_pm.vvd")
end