timer.Simple( 25, function()
timer.Simple(0.5,function()
RunConsoleCommand("gmod_mcore_test", 1)
RunConsoleCommand('r_fastzreject', -1)
end)
timer.Simple(1,function()
RunConsoleCommand('cl_ejectbrass', 0)
RunConsoleCommand('Muzzleflash_light', 0)
RunConsoleCommand('in_usekeyboardsampletime', 0)
RunConsoleCommand("rope_shake", 0)
end)
timer.Simple(1.5,function()
RunConsoleCommand("rope_wind_dist", 0)
RunConsoleCommand( "mat_disable_ps_patch", 1 )
RunConsoleCommand( "mat_disable_fancy_blending", 1 )
end)
timer.Simple(2,function()
RunConsoleCommand( "r_decal_cullsize", 0 )
RunConsoleCommand( "r_decals", 2 )
RunConsoleCommand( "mp_decals", 2 )
RunConsoleCommand( "studio_queue_mode", 1 )
end)
timer.Simple(5,function()
RunConsoleCommand( "r_shadows", 1 )
end)
timer.Simple(2.5,function()
RunConsoleCommand( "mp_decals", 30 )
RunConsoleCommand( "mat_forceaniso", 0 )
RunConsoleCommand( "cl_phys_props_enable", 0 )
RunConsoleCommand( "mat_disable_bloom", 1 )
end)
timer.Simple(3,function()
RunConsoleCommand( "cl_phys_props_max" , 0 )
RunConsoleCommand( "props_break_max_pieces" , 0 )
RunConsoleCommand( "r_propsmaxdist" , 0 )
end)
timer.Simple(3.5,function()
RunConsoleCommand( "violence_agibs" , 0 )
RunConsoleCommand( "violence_hgibs" , 0 )
RunConsoleCommand("cl_threaded_client_leaf_system", 1)
end)
timer.Simple(4,function()
RunConsoleCommand("r_threaded_client_shadow_manager", 1)
RunConsoleCommand("r_threaded_particles", 1)
RunConsoleCommand("r_threaded_renderables", 1)
RunConsoleCommand("r_queued_ropes", 1)
end)
timer.Simple(4.5,function()
RunConsoleCommand("joystick", 0)
RunConsoleCommand("violence_ablood", 0)
RunConsoleCommand("violence_hblood", 1)
RunConsoleCommand( "cl_show_splashes", 0 )
end)
timer.Simple(5.5,function()
RunConsoleCommand( "r_lod", 0 )
RunConsoleCommand( "r_shadowrendertotexture", 0 )
RunConsoleCommand( "r_shadowmaxrendered", 0 )
end)
timer.Simple(6,function()
RunConsoleCommand( "mat_shadowstate", 0 )
RunConsoleCommand("cl_threaded_bone_setup", 1)
RunConsoleCommand("rope_smooth", 0)
RunConsoleCommand("cl_detaildist", 0)
end)
timer.Simple(10,function()
if GetConVarNumber("3dskyoff") == 0 then
RunConsoleCommand("r_3dsky", 0)
end
end)
timer.Simple(6.5,function()
RunConsoleCommand("mat_bloomscale", 0)
RunConsoleCommand("mat_hdr_level", 0)
end)
timer.Simple(7,function()
RunConsoleCommand("mat_disable_lightwarp", 1)
RunConsoleCommand("r_drawmodeldecals", 0)
RunConsoleCommand("r_teeth", 0)
end)
timer.Simple(15,function()
RunConsoleCommand( "mat_queue_mode", -1 )
end)
timer.Simple(7.5,function()
RunConsoleCommand("cl_forcepreload", 1)
RunConsoleCommand("cl_detail_avoid_radius", 0)
RunConsoleCommand("net_compressvoice", 1)
end)
timer.Simple(12,function()
RunConsoleCommand("r_maxmodeldecal", 0)
RunConsoleCommand("r_drawdetailprops", 0)
RunConsoleCommand("r_eyemove", 0)
RunConsoleCommand("r_flex", 0)
end)
timer.Simple(8,function()
RunConsoleCommand("snd_mix_async", 1)
RunConsoleCommand("r_drawflecks", 0)
RunConsoleCommand("cl_showhelp", 0)
RunConsoleCommand("nb_shadow_dist", 0)
end)
timer.Simple(8.5,function()
RunConsoleCommand("demo_avellimit", 0)
RunConsoleCommand("r_maxdlights", 6)
RunConsoleCommand("cl_detailfade", 1)
end)
end)

hook.Add('InitPostEntity', 'azd',function()
	LocalPlayer():ConCommand('snd_restart; cl_drawmonitors 0; cl_tree_sway_dir .5 .5;r_drawflecks 1')
    hook.Remove("StartChat", "StartChatIndicator")
    hook.Remove("FinishChat", "EndChatIndicator")
end)

hook.Add("PrePlayerDraw", "afk", function(pl)

end)

timer.Create( "lerp_timer1", 1, 0, function()
    local ratio = 3
    local lerp = 120
    local online = #player.GetAll()
    if online > 75 then
        lerp = math.Clamp( online*ratio, 60, 250 )
    end
    RunConsoleCommand( "cl_interp",lerp/1000 )
end )

hook.Add("Tick", "dynlerp", function()
end)
