--leak by matveicher
--vk group - https://vk.com/codespill
--steam - https://steamcommunity.com/profiles/76561198968457747/
--ds server - https://discord.gg/7XaRzQSZ45
--ds - matveicher

// Copyright © 2012-2018 VCMod (freemmaann). All Rights Reserved. if you have any complaints or ideas contact me: steam - steamcommunity.com/id/freemmaann/ or email - freemmaann@gmail.com.

if !VC.Lng_T then VC.Lng_T = {} VC.Lng_T_Rev = {} end

local Lng = {}
Lng.Name = {"English", 'Specify this in your native language. Example: "Lietuvių", not "Lithuanian".'}
Lng.Language_Code = {"en", "Country code"}
Lng.Translated_By_Name = {"freemmaann", 'Your name.'}
Lng.Translated_By_Link = {"http://steamcommunity.com//id/freemmaann/", "Your steam link."}
Lng.Translated_Date = {"2016/05/26", "Date of which this was updated."}

Lng.BigThankYouToAllWhoHelpedTranslate = {"Big thank you to all who helped translate VCMod", ''}
Lng.WishToHelpTranslate = {"Wish to help translate? Click here.", ''}
Lng.Outdated = {"Outdated", ''}
Lng.Good = {"Good", ''}
Lng.TheName = {"Name", ''}
Lng.Overrides = {"Overrides", ''}
Lng.Tire = {"Tire", ''}
Lng.Light = {"Light", ''}
Lng.Revision = {"Revision", ''}
Lng.Compatibility = {"Compatibility", ''}
Lng.Use = {"Use", ''}
Lng.Disabled = {"Disabled", '"Test drive is diabled."'}
Lng.Overwritten = {"Overwritten", ''}
Lng.Status = {"Status", ''}
Lng.Override_Controls = {"Override controls", ''}
Lng.Date = {"Date", ''}
Lng.Effects = {"Effects", ''}
Lng.Logs = {"Logs", 'Logging events of VCMod.'}
Lng.Return = {"Return", ''}
Lng.Locked = {"Vehicle locked.", 'Vehicle has been locked.'}
Lng.UnLocked = {"Vehicle unlocked.", 'Vehicle has been unlocked.'}
Lng.FuelLidPosition = {'Fuel lid position', ''}
Lng.Chat = {'To adjust options (car lights, view) type "!vcmod" in chat.', 'You seen this menu in chat when entering a vehicle.'}
Lng.Broken = {"This vehicle is broken, it needs to be repaired.", 'You see this when entering a broken vehicle.'}
Lng.AutoEnter = {"Automatically enter", ''}
Lng.LimitReturnDistance = {"Limit return distance", ''}
Lng.AutoReturnOnDisconnect = {"Automatically return vehicles on disconnect", ''}
Lng.Trl_Atch = {"Trailer attached.", 'When attaching a trailer. "This trailer has been attached."'}
Lng.Trl_Detch = {"Trailer detached.", 'When detaching a trailer. "This trailer has been detached."'}
Lng.ELS_TuningIntoPoliceC = {"Tuning into police chatter", 'When entering an emergency vehicle displayed in chat.'}
Lng.ELS_NoPoliceRCFound = {"No police chatter found.", 'When failed to find a police chatter stream when entering an emergency vehicle.'}
Lng.All = {"All", '"All vehicles have been spawned."'}
Lng.Apply = {"Apply", ''}
Lng.Added = {"Added", 'Added something to something.'}
Lng.Done = {"Done", 'Done doing something.'}
Lng.Updates = {"Updates", ''}
Lng.UpdatesAreAppliedAutomaticallyAfterMapRestart = {"Updates are applied automatically after map restart.", ''}
Lng.UnknownVehicle = {"Unknown Vehicle", 'When entering a vehicle.'}
Lng.Close = {"Close", '"To close this menu."'}
Lng.LoadFromFile = {"Load from file", ''}
Lng.Engine = {"Engine", ''}
Lng.Available = {"Available", '"These vehicles are available to be purchased."'}
Lng.JobRelated = {"Job related", ''}
Lng.Buy = {"Buy", '"You can buy this vehicle."'}
Lng.Sell = {"Sell", 'You can sell this vehicle.'}
Lng.Paintjob = {"Paint job", 'Vehicles paint job, in other words, its skin.'}
Lng.Spawn = {"Spawn", '"I am able to spawn thing vehicle."'}
Lng.Purchase = {"Purchase", '"You are able to purchase this vehicle."'}
Lng.Purchased = {"Purchased", '"This vehicle has been purchased."'}
Lng.TestDrive = {"Test drive", '"You can test drive this vehicle."'}
Lng.Allowed = {"Allowed", '"Was allowed to do something."'}
Lng.NotAllowedRemoveOtherVehicles = {"Not allowed, remove other spawned vehicles.", '""'}
Lng.AccessRestricted = {"Access restricted.", '"Your access has been restricted. In other words, denied."'}
Lng.CantBeUsedBy = {"Can't be used by", '"Used in car dealer when someone is trying to use something they dont have access to."'}
Lng.CantBeSpawnedBy = {"Can't be spawned by", '"Used in car dealer when someone is trying to spawn something they dont have access to."'}
Lng.OriginalPrice = {"Original price", '"Vehicles original price."'}
Lng.RefundPercentage = {"Refund percentage", 'The percentage you receive when selling the vehicle from the original price.'}
Lng.SellingPrice = {"Selling price", 'For what price it will be sold.'}
Lng.Free = {"Free", '"This addon is free."'}
Lng.Humming = {"Humming", 'Humming, as in singing quitly.'}
Lng.Persistent = {"Persistent", 'Constantly staying on or not wanting to change.'}
Lng.TowingNotAllowTooFar = {"Not allowed to tow if too far", 'Car can not be towed back if its too far away.'}
Lng.TooFar = {"Too far", 'Something is not close enough.'}
Lng.Blurred = {"Blurred", 'Blurry, smudged.'}
Lng.CoreOptions = {"Core options", ''}
Lng.RM_Settings = {"Repair Man options", ''}
Lng.HoldUseToPickup = {"Hold [USE] to pick up", ''}
Lng.YouAlreadyHaveSpikestrip = {"You already have spike strip", ''}
Lng.RepairMan = {"Repair Man", ''}
Lng.NoneAdmin = {"None administrator", ''}
Lng.AdminControlsCanBeAlteredBy = {"Administrator controls can be altered by:", ''}
Lng.RMPlaced = {"Repair man placed", ''}
Lng.Rays = {"NoneFound", '"None found."'}
Lng.Rays = {"Rays", '"These light rays are blinding."'}
Lng.Rotate = {"Rotate", '"Rotate this object around."'}
Lng.customisation = {"customization", 'To alter, change something, customize.'}
Lng.Sold = {"Sold", '"This vehicle has been sold."'}
Lng.Tab = {"Tab", 'Same as the "Vehicle tab" or "NPC tab" you see in the Q menu.'}
Lng.Previous = {"Previous", 'A thing before that. "Previous vehicle."'}
Lng.Next = {"Next", 'A thing after that. "Next vehicle."'}
Lng.RepairingVehicleAdmin = {"Admin: repairing vehicle", ''}
Lng.Active = {"Active", ''}
Lng.Idle = {"Idle", ''}
Lng.TouchBrokenCarPiece = {"Touch broken car piece", ''}
Lng.Pumping = {"Pumping", ''}
Lng.FuelTaken = {"Fuel taken", ''}
Lng.DroppedFuel = {"Fuel dropped", ''}
Lng.Wheels = {"Wheels", ''}
Lng.critical = {"critical", ''}
Lng.destroyed = {"destroyed", ''}
Lng.damaged = {"damaged", ''}
Lng.Repairs = {"Repairs", ''}
Lng.DamagedParts = {"Damaged parts", ''}
Lng.EngineNew = {"Engine new", ''}
Lng.SelectVehicle = {"Select a vehicle", ''}
Lng.YourVehiclesRepairsComplete = {"Your vehicle repairs are complete.", ''}
Lng.severelydamaged = {"severely damaged", ''}
Lng.YourVehiclesRepairsFailed = {"Your vehicle repair have failed", ''}
Lng.sec = {"sec", ''}
Lng.RepairSpeedMult = {"Repair speed multiplier", ''}
Lng.NeedVehiclePart = {"Need a vehicle part", ''}
Lng["Front left"] = {"Front left", 'Keep this etremely short.'}
Lng["Front right"] = {"Front right", 'Keep this etremely short.'}
Lng["Rear left"] = {"Rear left", 'Keep this etremely short.'}
Lng["Rear right"] = {"Rear right", 'Keep this etremely short.'}
Lng.Repairing = {"Repairing", ''}
Lng.Prices = {"Prices", ''}
Lng.PartsCost = {"Parts cost", ''}
Lng.RepairCost = {"Repair cost", ''}
Lng.RepairTime = {"Repair time", ''}
Lng.Total = {"Total", ''}
Lng.OutOfFuel = {"Out of fuel", ''}
Lng.FuelRemaining = {"Fuel remaining", ''}
Lng.Function = {"Function", ''}
Lng.TestDriveEnded = {"Test drive ended.", '"Test drive has ended."'}
Lng.EndTestDrive = {"End test drive", 'Button text. "To end a test drive."'}
Lng.Error = {"Something went wrong.", ""}
Lng.Respawn = {"Respawn", ""}
Lng.Create = {"Create", ""}
Lng.CantRemoveThisWay = {"Can't remove this way.", ""}
Lng.Price = {"Price", ""}
Lng.Add = {"Add", ""}
Lng.OnlyAllowOneCarToBeSpawnedPerCarDealerPerUser = {"Only allow one car to be spawned per car dealer per user", ""}
Lng.StoreInformation = {"Store information", "This car dealer will star information like fuel and health state of the vehicle."}
Lng.TextViewDistance = {"Text view distance", ""}
Lng.DetectDistance = {"Detect distance", ""}
Lng.TowingCost = {"Towing cost", ""}
Lng.RefundPricePerc = {"Refund price %", ""}
Lng.VehiclesCanBeRemovedByTool = {"Vehicles can be removed by tool", ""}
Lng.CD_Cant_Afford = {"You can not afford this.", ''}
Lng.ReachedMaxCapacity = {"Reached maximum capacity", ''}
Lng.CD_Loading = {"Keep calm, car dealer is loading.", ''}
Lng.VehicleBought = {"Vehicle has been bought.", ''}
Lng.ParkingLotsTaken = {"All parking lots taken.", ''}
Lng.NoVehiclesFound = {"No vehicles found", ''}
Lng.VehicleSpawned = {"Vehicle has been spawned", ''}
Lng.AreYouSureYouWantToSell = {"Are you sure you want to sell", ''}
Lng.TestDriveTimeLeft = {"Test drive time left", ''}
Lng.SpawnedVehicle = {"Spawned vehicle", ''}
Lng.FirstReturnTheVehicle = {"You have to return the vehicle first.", ''}
Lng.VehicleReturned = {"Vehicle returned.", ''}
Lng.VehicleTowedFor = {"Vehicle towed for", ''}
Lng.YouHaveToBeAdmin = {"You have to be an administrator.", ''}
Lng.CDPlaced = {'Car dealer placed', ''}
Lng.Deleted = {'Successfully deleted', ''}
Lng.CDsPlaced = {"All car dealer's respawned.", ''}
Lng.CDSpawnedIncorrectly = {"Car dealer has been spawned incorrectly.", ''}
Lng.NoCloseVehicles = {"No nearby vehicles available.", ''}
Lng.PosChanged = {"Positions changed.", ''}
Lng.TouchCarWithThis = {"Touch a car using this for it to take affect.", ''}
Lng.Info = {"Info", '"Information"'}
Lng.Menu = {"Menu", '"Open this menu."'}
Lng.Author = {"Author", ''}
Lng.NoCDFound = {"No car dealer found", ''}
Lng.Language = {"Language", ''}
Lng.Personal = {"Personal", ''}
Lng.Administrator = {"Administrator", ''}
Lng.SuperAdmin = {"Super administrator", ''}
Lng.Options = {"Options", ''}
Lng.ELSOptions = {"ELS options", ''}
Lng.Main = {"Main", '"Main lights."'}
Lng.Controls = {"Controls", ''}
Lng.Accept = {"Accept", ''}
Lng.Cancel = {"Cancel", ''}
Lng.HUD = {"HUD", ''}
Lng.CruisingAt = {"Cruising at", ''}
Lng.Damage_Repair_GiveWrenchToDriver = {"Give repair wrench to driver", ''}
Lng.Damage_Repair_GiveWrenchToCarPartUser = {"Give repair wrench on vehicle part use", ''}
Lng.Damage_Repair_NeedPart = {"Repairing with wrench needs vehicle part", ''}
Lng.View = {"View", ''}
Lng.Advanced = {"Advanced", ''}
Lng.Lerp = {"Lerp", ''}
Lng.ThirdPView = {"Radio", ''}
Lng.FlatTire = {"Flat tire", ''}
Lng.Radio = {"Radio", ''}
Lng.Multiplier = {"Multiplier", 'A thing that multiplies things.'}
Lng.OptOnly_You = {"These options will only affect you", ''}
Lng.OptOnly_Admin = {"These settings can only be changed by an administrator", ''}
Lng.OptOnly_SuperAdmin = {"These settings can only be changed by a super administrator", ''}
Lng.CD_Settings = {"Car dealer", ''}
Lng.Normal = {"Normal", ''}
Lng.Skidding = {"Skidding", ''}
Lng.Sparks = {"Sparks", ''}
Lng.TireTracks = {"Tire tracks", ''}
Lng.Height = {"Height", ''}
Lng.PerformanceImpact = {"Performance impact", ''}
Lng.Detail = {"Detail", ''}
Lng.SpeedTilt = {"Speed tilt", ''}
Lng.FadeOutTime = {"Fade out time", 'Time after which things start to become dimmer and dimmer.'}
Lng.FadeOutDistance = {"Fade out distance", 'Distance at which things start to become dimmer and dimmer.'}
Lng.Reset = {"Reset", ''}
Lng.Save = {"Save", ''}
Lng.Load = {"Load", ''}
Lng.Map = {"Map", ''}
Lng.Volume = {"Volume", 'How load a thing is.'}
Lng.LockFromInside = {"Lock vehicle from inside", ''}
Lng.ThirdPersonViewSeeThroughProps = {"Third person view allows players to see through props", ''}
Lng.LimitDriveByView = {"Limit drive by view", 'While in drive by if it should limite the player view rotation.'}
Lng.Distance = {"Distance", ''}
Lng.CantSwitchFromThisSeat = {"Can't change seats from this seat.", ''}
Lng.CantSwitchToFront = {"You can not switch to front.", ''}
Lng.CantExitWhileLocked = {"Can't exit while vehicle is locked.", ''}
Lng.None = {"None", ''}
Lng.Loading = {"Loading...", ''}
Lng.EnterKey = {"Enter key", '"Please anter a key."'}
Lng.Enabled_Cl = {"Enabled clientside", ''}
Lng.Enabled_Sv = {"Enabled serverside", ''}
Lng.Lights = {"Lights", ''}
Lng.Health = {"Health", ''}
Lng.Sound = {"Sound", ''}
Lng.Other = {"Other", ''}
Lng.CreatedBy = {"Created by", ''}
Lng.Enabled = {"Enabled", ''}
Lng.OffTime = {"Off time", 'Time in which it will be off.'}
Lng.Time = {"Time", ''}
Lng.DistMultiplier = {"Distance multiplier", ''}
Lng.ControlsReset = {"Controls reset.", ''}
Lng.SettingsSaved = {"Settings saved.", ''}
Lng.SettingsReset = {"Settings reset.", ''}
Lng.LoadedSettingsFromServer = {"Settings loaded from server.", ''}
Lng.InteriorIndicators = {"Interior indicators", 'Indicators that are inside of a vehicle.'}
Lng.ExtraGlow = {"Extra glow", ''}
Lng.ManualSiren = {"Manual siren", ''}
Lng.ELSSirenSwitch = {"ELS siren switch", ''}
Lng.ELSSirenToggle = {"ELS siren toggle", ''}
Lng.ELSLightsSwitch = {"ELS lights switch", ''}
Lng.ELSLightsToggle = {"ELS lights toggle", ''}
Lng.VCModMainEnabled = {"VCMod main enabled", ''}
Lng.VCModELSEnabled = {"VCMod ELS enabled", ''}
Lng.ELSLightsEnabled = {"ELS lights enabled", ''}
Lng.AutoDisableELSLights = {"Auto disable ELS lights", ''}
Lng.OffOnExit = {"Off on exit", ''}
Lng.Siren = {"Siren", ''}
Lng.AutoDisableELSSounds = {"Auto disable ELS sounds", ''}
Lng.Manual = {"Manual", ''}
Lng.AdvancedDamage = {"Advanced damage", ''}
Lng.Damage_Lights = {"Can damage lights", ''}
Lng.Damage_Wheels = {"Can damage tires", ''}
Lng.Damage_Wheels_ELSOff = {"ELS vehicles have bullet-proof tires", ''}
Lng.Damage_Exhaust = {"Can damage exhaust", ''}
Lng.Damage_Exhaust_Backfire = {"Can backfire", ''}
Lng.Damage_FuelLid = {"Can damage fuel lid", ''}
Lng.Damage_Custom_Sounds = {"Custom collision sounds", ''}
Lng.SpikeStrip_auto_give_els = {"Spike strip auto given in ELS vehicles", ''}
Lng.Spikestrip = {"Spike strip", ''}
Lng.SpikeStrip_auto_remove_death = {"Spike strip auto remove when player dies", ''}
Lng.CanDamagePlayersNPCs = {"Can damage players/NPCs", ''}
Lng.IgnoreEmergencyVehicles = {"Ignore emergency vehicles", ''}
Lng.Explode = {"Explode", ''}
Lng.Off = {"Off", ''}
Lng.Light_Damage = {"Light damaged", ''}
Lng.Light_Damaged = {"Light damaged, use sparks", 'The sparks when a light is damaged but is attempted to be used.'}
Lng.Exhaust_Damage = {"Exhaust damaged", ''}
Lng.Wheel_Damage = {"Tire damaged", ''}
Lng.Damage_Sparks_Damage = {"Collision sparks", ''}
Lng.Explosion_Custom = {"Custom explosion", ''}
Lng.Exhaust_Custom = {"Custom exhaust", ''}
Lng.Brake_Effects = {"Brake/sliding - effects, tire tracks, sounds", ''}
Lng.On = {"On", ''}
Lng.Bullhorn = {"Bullhorn", ''}
Lng.PoliceChatterEnabled = {"Police chatter enabled", ''}
Lng.PoliceChatter = {"Police chatter", ''}
Lng.PoliceChatter_Info = {"Police chatter is a real time feed of official police chatter VIA radio.", ''}
Lng.SelectedRadioChatter = {"Selected radio chatter channel", ''}
Lng.ReduceDamageToEmergencyVehicles = {"Reduce damage to emergency vehicles", ''}
Lng.Repair = {"Repair", ''}
Lng.YouAreUsingVCMod = {"You are using VCMod", ''}
Lng.ServerIsUsingVCMod = {"This server is using VCMod", ''}
Lng.Info_EverThought = {"Ever thought that Garrysmod's vehicles are lacking realism?", ''}
Lng.Info_VCModIsDesigned = {"VCMod is designed to provide Garrysmod's vehicle with full assortment of features.", ''}
Lng.Info_VCModHasFollowingAddons = {"VCMod has the following addons:", ''}
Lng.WhyISellVCMod = {"Why VCMod is for sale", ''}
Lng.VisDist = {"Visibility distance", ''}
Lng.Warmth = {"Warmth", ''}
Lng.Lines = {"Lines", ''}
Lng.Glow = {"Glow", ''}
Lng.DynamicLights = {"Dynamic lights", ''}
Lng.ThirdPersonView = {"Third person view", ''}
Lng.DynamicView = {"Dynamic view", ''}
Lng.AutoFocus = {"Auto focus", ''}
Lng.Reverse = {"Reverse", ''}
Lng.VectorStiffness = {"Vector stiffness %", ''}
Lng.AngleStiffness = {"Angle stiffness %", ''}
Lng.TruckView = {"Truck connected view", ''}
Lng.HoldDuration = {"Hold duration", ''}
Lng.HoldKey = {"Hold key", ''}
Lng.SwitchSeats = {"Switch seats:", ''}
Lng.KickPeopleOut = {"Kick people out:", ''}
Lng.OpenMenu = {"Open menu", ''}
Lng.Body = {"Body", ''}
Lng.Steering = {"Steering", ''}
Lng.FrontAxle = {"Front Axle", ''}
Lng.RearAxle = {"Rear Axle", ''}
Lng.Mouse = {"Mouse", ''}
Lng.KeyboardInput = {"Keyboard input", ''}
Lng.MouseInput = {"Mouse input", ''}
Lng.RunningLights = {"Running lights", ''}
Lng.HeadLights = {"Head lights", ''}
Lng.FogLights = {"Fog lights", ''}
Lng.Handling = {"Handling", ''}
Lng.LowHighBeamToggle = {"Low/High beams", ''}
Lng.LowHigh = {"Low/High beam toggle", ''}
Lng.LowBeams = {"Low beams", ''}
Lng.HighBeams = {"High beams", ''}
Lng.HighBeamsFlash = {"High beams flash", ''}
Lng.HazardLights = {"Hazard lights", ''}
Lng.BlinkerLeft = {"Blinker left", ''}
Lng.BlinkerRight = {"Blinker right", ''}
Lng.Exhaust_Effect_BackFireHealthLow = {"Exhaust backfires if health is low", ''}
Lng.Horn = {"Horn", ''}
Lng.Cruise = {"Cruise", ''}
Lng.LockUnlock = {"Lock/Unlock", ''}
Lng.LookBehind = {"Look behind", ''}
Lng.DetachTrailer = {"Detach trailer", ''}
Lng.Wipers = {"Wipers", ''}
Lng.Weaponry = {"Weaponry", ''}
Lng.AuxiliaryLights = {"Auxiliary Lights", ''}
Lng.Effect3D = {"3D effect", ''}
Lng.PickupDistance = {"Pickup text draw distance", ''}
Lng.HUDHeight = {"Side HUD height %", ''}
Lng.Icons = {"Icons", ''}
Lng.Drain_Fuel = {"Drain fuel", ''}
Lng.HUD_MPH = {"mi/h instead of km/h", ''}
Lng.ELS_Siren = {"ELS siren", ''}
Lng.CanShootPlayersInSeats = {"Can shoot players inside vehicles", ''}
Lng.CanShootPlayersInSeatsOverrideDefault = {"Can shoot players inside vehicles, override default", ''}
Lng.HitLikelinessMult = {"Hit likeliness mult", ''}
Lng.Empty = {"Empty", ''}
Lng.hour = {"hour", 'As in 20 liters / hour'}
Lng.g_gallons = {"gal", 'Short of the word Gallons'}
Lng.g_liters = {"l", 'Short of the word Liters'}
Lng.Parts = {"Parts", ''}
Lng.ForceFirstPersonView = {"Force first person view", ''}
Lng.Update = {"Update", ''}
Lng.ELS_Lights = {"ELS lights", ''}
Lng.HandbrakeLights = {"Handbrake lights", ''}
Lng.EnterDriveByMode = {"Shoot out of the window", ''}
Lng.DriveBy = {"Drive By mode for passengers", ''}
Lng.ExitDriveByMode = {"Stop shooting out of the window", ''}
Lng.Damage_Ignite = {"Ignite vehicle after explosion", ''}
Lng.MinimumSpeed = {"Minimum speed", ''}
Lng.Currency = {"Currency", ''}
Lng.Everything = {"Everything", ''}
Lng.InteriorLights = {"Interior lights", ''}
Lng.CanNotEquipThisWeapon = {"Can not equip this weapon", ''}
Lng.BlinkersOffExit = {"Blinkers (turn signals) off on exit", ''}
Lng.Imperialinsteadofmetric = {"Use imperial system instead of metric", ''}
Lng.DamageEnabled = {"Damage enabled", ''}
Lng.StartHealthMultiplier = {"Start health multiplier", ''}
Lng.PhysicalDamage = {"Physical damage", ''}
Lng.OnlyWithPassengers = {"Only with passengers", ''}
Lng.HealthRepairBulletDamage = {"Attempt to repair default source bullet damage", ''}
Lng.FireDuration = {"Fire duration", ''}
Lng.RemoveDestroyedVehicle = {"Remove destroyed vehicle", ''}
Lng.CanEnterIfDestroyed = {"Can enter if destroyed", ''}
Lng.EmitSmoke = {"Emit smoke", ''}
Lng.CarsCantRunOverPlayers = {"Cars can't damage players", ''}
Lng.ReducePlayerDmgWhileInCar = {"Reduce player damage while in a car", ''}
Lng.DoorSounds = {"Door sounds", ''}
Lng.TruckRevBeep = {"Truck reverse sound", ''}
Lng.OverrideDefaultSteeringLockOnExit = {"Override default steering lock on exit", ''}
Lng.OverrideDefaultBrakesOnExit = {"Override default brakes on exit", ''}
Lng.MatchPlayerSpeedExit = {"Match player speed on exit", ''}
Lng.NoCollidePlyOnExit = {"No collide players with car on exit", ''}
Lng.PlayersGetDamagedOnExit = {"Players get damaged on exit", ''}
Lng.kWh = {"kWh", 'Kilo what hour'}
Lng.Fuel = {"Fuel", ''}
Lng.Exhaust = {"Exhaust", ''}
Lng.PassengerSeats = {"Passenger seats", ''}
Lng.Diesel = {"Diesel", 'Fuel type.'}
Lng.Fuel_Cons_Mult = {"Fuel consumption multiplier", ''}
Lng.Refuel_Mult_Station = {"Refueling speed multiplier using station", ''}
Lng.Refuel_MaxCapacity = {"Refueling station maximum capacity", ''}
Lng.Fuel_StartMult = {"Initial amount multiplier", ''}
Lng.Refuel_Mult_Hand = {"Refueling speed multiplier using hands", ''}
Lng.Fuel_Pickup_Pickup = {"Can pick up fuel canisters", ''}
Lng.Fuel_Pickup_Explode = {"Fuel canisters can explode", ''}
Lng.Fuel_Pickup_Touch = {"Fuel canisters can refuel by touch", ''}
Lng.Fuel_Pickup_Touch_Elec = {"Fuel canisters can refuel by touch (Electricity)", ''}
Lng.Fuel_Pickups_Beside_Stations = {"Place fuel canisters besides fuel stations", ''}
Lng.Petrol = {"Petrol", 'Fuel type.'}
Lng.Electricity = {"Electricity", ''}
Lng.Elec = {"Elec", 'Electricity shortened.'}
Lng.Pickup_Repair = {"Vehicle repair :val:", 'This is used in pickup entities.\n\n:val: will be replaced by the percentage.'}
Lng.Pickup_Fuel = {"Vehicle fuel: ", 'This is used in pickup entities.'}
Lng.Pickup_PartKit = {"Part kit", 'Box of parts (entity).'}
Lng.Pickup_Carpart = {"Vehicle part: ", 'This is used in pickup entities.'}
Lng.liters = {"liters", 'Volume, as in, 20 liters of water.'}
Lng.gallons = {"gallons", 'Volume, as in, 20 gallons of water.'}
Lng.AbleToSwitch = {"Can switch from inside", ''}
Lng.TrailerAttach = {"Trailer attach", ''}
Lng.TrailerAttachConStrengthM = {"Trailer attach connection strength multiplier", ''}
Lng.TrailersCanAtchToReg = {"Trailer can attach to regular cars", ''}
Lng.RepairToolSpeedMult = {"Repair tool speed multiplier", ''}

VC.Lng_Default = Lng
VC.Lng_Default_Count = table.Count(VC.Lng_Default)

local TempLng = {} for k,v in pairs(Lng) do TempLng[k] = v[1] end
VC.Lng_T[Lng.Language_Code[1]] = TempLng VC.Lng_T_Rev[Lng.Language_Code[1]] = 1

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

function VC.Lng(msg)
	if VC.Lng_Sel and VC.Lng_T[VC.Lng_Sel] and VC.Lng_T[VC.Lng_Sel][msg] then
		msg = VC.Lng_T[VC.Lng_Sel][msg]
	else
		msg = VC.Lng_T["en"][msg] or msg
	end

	return msg
end

--leak by matveicher
--vk group - https://vk.com/codespill
--steam - https://steamcommunity.com/profiles/76561198968457747/
--ds server - https://discord.gg/7XaRzQSZ45
--ds - matveicher
